// GENERATED by fakefish-gen-constants from shared/stim_constants.json — DO NOT EDIT.
//
// Playback / session constants shared by the fakefish surfaces. Edit
// shared/stim_constants.json and re-run `uv run fakefish-gen-constants`.
//
// The SAMPLE RATE is not defined here — it comes from eel_stimuli.h
// (STIM_SAMPLE_RATE_HZ), so it is stated exactly once in the whole repo. Every
// sample-unit figure below is derived from it by the preprocessor.
//
// ONE MARKER, AND ONLY THE SD DEVICE HAS IT:
//   SD_MARKER_*    6 pulses at a fixed 10 Hz with ALTERNATING polarity, baked into
//                  the WAV card by build_sd_card.py. Identifies a playback. It is that
//                  device's ONLY record — it writes no pulse log.
//   The RC device had a count-coded 100 Hz burst until 2026-08-22. Removed: its log is
//   a precondition for output, and a SHAM was emitting four pulses before going quiet.
#pragma once
#include <stdint.h>
#include "eel_stimuli.h"   // STIM_SAMPLE_RATE_HZ — the one place the rate is defined

// ===== SD path — levels baked into the WAV card ============================
// Absolute output levels as a fraction of full scale (NOT peak-normalised): the
// loc/volley/marker ratios are the experiment, so they must survive rendering.
#define SD_LEVEL_VOLLEY       0.9f
#define SD_LEVEL_LOC          0.225f
#define SD_LEVEL_CALIBRATION  0.45f
#define SD_LEVEL_MARKER       0.5f

// ===== SD path — the alternating-polarity pulse marker =====================
// The lead-in that identifies a playback: SD_MARKER_N_PULSES EOD pulses at a fixed
// IPI, with the polarity ALTERNATING pulse to pulse. Alternation is the discriminator
// (no eel alternates; a localization train is single-polarity) and it survives the
// firmware's per-press random polarity flip, which negates the whole WAV. The pulse
// count is EVEN so the burst carries no net charge.
#define SD_MARKER_N_PULSES    6
#define SD_MARKER_RATE_HZ     10.0f
#define SD_MARKER_IPI_SAMP    5000u   // 100 ms
#define SD_MARKER_SAMP        ((uint32_t)SD_MARKER_IPI_SAMP * (SD_MARKER_N_PULSES - 1) + EOD_HV_LEN)

// ===== SD path — program A, the calibration train ==========================
// A steady SINGLE-polarity EOD train at a known rate and level: a plain reference
// signal, deliberately not a code.
#define SD_CAL_RATE_HZ        50.0f
#define SD_CAL_IPI_SAMP       1000u
#define SD_CAL_S              10
#define SD_CAL_SAMP           ((uint32_t)SD_CAL_S * STIM_SAMPLE_RATE_HZ)

// ===== SD path — session structure =========================================
// Seconds are the authored unit; sample units are derived from STIM_SAMPLE_RATE_HZ.
#define SD_SESSION_LOC_S         20   // localization window (program B)
#define SD_SESSION_D_LOC_S       5    // localization lead (program D)
#define SD_SESSION_D_GAP_MS      300  // loc -> volley gap (program D)
#define SD_SESSION_LOC_SAMP      ((uint32_t)SD_SESSION_LOC_S    * STIM_SAMPLE_RATE_HZ)
#define SD_SESSION_D_LOC_SAMP    ((uint32_t)SD_SESSION_D_LOC_S  * STIM_SAMPLE_RATE_HZ)
#define SD_SESSION_D_GAP_SAMP    ((uint32_t)SD_SESSION_D_GAP_MS * STIM_SAMPLE_RATE_HZ / 1000u)

// Nominal open-circuit pulse peak at full scale. NOT a calibrated field strength —
// in water the source impedance divides against the load. Operator-set nominal only.
#define SD_FULLSCALE_PULSE_PEAK_MV 3313.0f

// ===== RC path — NO MARKER ================================================
// The RC device emitted a count-coded EOD burst before every trial (2 pulses volley,
// 4 sham, 100 Hz) until 2026-08-22. PULSE_MARKER_* is gone: the per-pulse SD log is a
// precondition for output, so the trial was already recorded — and for a SHAM the burst
// was not redundant at all, it was a stimulus in the no-stimulus control.
// The SD device keeps SD_MARKER_* above; it has no log, so its lead-in is the only
// record a playback happened.

// ===== RC path — blinded THREE-ARM trial draw ==============================
// The trigger fires in ONE direction and does not say WHICH arm to run; the firmware
// draws at playback time, so the operator cannot choose and their timing cannot
// correlate with the arm. The draw happens in the sample-clock ISR, never in loop(),
// because random() must stay single-caller.
//
//   VOLLEY   — a library discharge (the treatment)
//   BASELINE — resting-rhythm pulses at localization amplitude: a fish is present and
//              NOT hunting. This is the arm that separates 'a discharge happened' from
//              'a fish is there at all', which a volley-vs-nothing design confounds.
//   SILENCE  — nothing at all (what the two-arm design called a SHAM).
//
// All three last the SAME length: every trial draws a volley item and the two silent
// arms hold for exactly its duration, so the arms match in duration BY CONSTRUCTION.
// Weights are per-mille and sum to 1000 (gen_constants.validate enforces it); the C
// draws random(TRIAL_DRAW_RANGE) once and walks the two cutoffs in this order.
#define TRIAL_W_VOLLEY_MILLI   334   // per-mille; the three sum to 1000
#define TRIAL_W_BASELINE_MILLI 333
#define TRIAL_W_SILENCE_MILLI  333
#define TRIAL_DRAW_RANGE       1000   // draw random(TRIAL_DRAW_RANGE)...
#define TRIAL_CUT_VOLLEY       (TRIAL_W_VOLLEY_MILLI)                          // ...< this = VOLLEY
#define TRIAL_CUT_BASELINE     (TRIAL_W_VOLLEY_MILLI + TRIAL_W_BASELINE_MILLI) // ...< this = BASELINE, else SILENCE

// The BASELINE arm's own rhythm knobs, deliberately NOT the CH3/CH5 controls: the
// control condition is 'a resting eel', not 'a resting eel at whatever tempo the knob
// was left at' — and the arm must work with live localization switched fully off,
// which is exactly when CH3 reads REST. 3.15 Hz is the measured animal.
#define TRIAL_BASE_TICK_HZ     3.15f
#define TRIAL_BASE_RANDOMNESS  1.0f

// ===== RC path — amplitude =================================================
// The control sets the VOLLEY (max); localization is DERIVED as volley / ratio.
#define VOLLEY_AMP_RATIO   4.0f
#define MASTER_AMP_MIN     0.0f
#define MASTER_AMP_MAX     1.0f
#define PANEL_VOLLEY_AMP   1.0f // bench default (no transmitter)

// ===== RC path — live localization train ===================================
// The RHYTHM is the fitted model (loc_model_params.h + loc_rhythm.h); these are only
// the ranges the operator's knobs span.
//
// CH3 is a TICK TEMPO — one over the median interval — not an average pulse rate. The
// measured eel ticks at LOC_NOMINAL_TICK_HZ (3.15 Hz). Under the retired lognormal a
// setting of 5 Hz meant 5 pulses/s on average; it now means the fish ticks at 5 Hz,
// which delivers about 3.3 pulses/s once the heavy tail is included.
//
// The ladder between these two is LOGARITHMIC (rc_rate_to_hz), so every rung is the same
// RATIO from its neighbours. A linear one spent ~85 % of the throttle's travel above
// anything a real eel does and pushed the slow settings into the sliver of travel just
// above the fail-safe cutoff. Geometric spacing puts the measured eel at mid-throttle
// (sqrt(0.5 * 20.0) = 3.16 Hz) and gives ~0.1 Hz steps near 1 Hz.
#define LOC_RATE_MIN_HZ    0.5f
#define LOC_RATE_MAX_HZ    20.0f
#define PANEL_RATE_HZ      5.0f
// CH5 bench default. 1.0 IS the measured eel (0 = metronome, useful to ~1.5). This is
// NOT the retired jitter CV: it scales the state score, so it changes how MUCH the rate
// varies without touching how it varies over time.
#define PANEL_RANDOMNESS   1.0f
// Minimum IPI. MUST stay > EOD_HV_LEN so localization pulses can never overlap —
// that invariant is what lets locgen.h use a single-pulse scheduler.
//
// This is the RESTING/VOLLEY ANTIMODE, not an arbitrary margin. The model's interval
// table is clamped to it in SCORE space, but rate is a pure TIME dilation, so any
// tick tempo above the nominal 3.15 Hz scales that floor down with everything else
// (4.4 ms at CH3 = 20 Hz). Since the source analysis separates resting pulses from
// fast runs on exactly this antimode, an unfloored fast train would emit intervals
// that read as micro-bursts of our own making.
#define LOC_REFRACTORY_SAMP 1250u  // 25 ms @ 50 kHz
