// GENERATED by tools/export_teensy_stimuli.py — do not edit by hand.

#pragma once
#include <stdint.h>
#include <stddef.h>  // NULL

#define STIM_FORMAT_VERSION   4
#define STIM_SAMPLE_RATE_HZ   50000

// ---- EOD waveform (device-agnostic) --------------------------------------
// Signed int16, |peak| == 32767, endpoints 0. Each firmware maps a sample to
// its output by splitting the sign across two channels (3.5: two DACs; 4.1: two
// PWM+RC channels) -> a bipolar differential drive; both phases render (the
// negative phase on the second channel), and which channel leads encodes polarity.
// Near-monophasic (net integral is positive) -> polarity is a firmware choice,
// constant within a playback, randomised between playbacks.
#define EOD_HV_LEN  131
#define EOD_NET_INTEGRAL_X1000  41577   // informational DC-load metric
extern const int16_t EOD_HV[EOD_HV_LEN];

// ---- Stimulus item library (TIMING + relative amplitude, NO absolute amp) -
// ipi_samp[i] = samples to WAIT BEFORE pulse i (ipi_samp[0]==0). rel_amp[i] is
// the per-pulse relative voltage 0..255 (==0..1.0); rel_amp==NULL means every
// pulse is full-scale. Absolute amplitude is a firmware GLOBAL scale.
typedef enum {
  STIM_REAL_VOLLEY=0, STIM_SYNTH_VOLLEY=1, STIM_LOCALIZATION=2
} StimKind;
typedef struct {
  const uint32_t* ipi_samp;   // length n; wait-before-pulse in samples; [0]=0
  const uint8_t*  rel_amp;    // length n; 0..255; NULL => all full-scale
  uint16_t        n;          // number of pulses
  uint8_t         kind;       // StimKind
  uint8_t         group;      // per-source provenance id (reserved)
} StimItem;
#define N_STIM_ITEMS  113
extern const StimItem STIM_ITEMS[N_STIM_ITEMS];

// ---- Per-item sine-marker lead-in gap ------------------------------------
// STIM_LEAD_GAP_SAMP[i] = samples of SILENCE the driver plays between the sine
// sine marker and item i's first pulse. Randomly chosen once at export (seeded,
// deterministic) then FIXED per item — so the marker's recorded offset plus this
// known gap locates/identifies the item downstream. Driver-level (a silent lead;
// the overlap-add engine never sees it). Parallel to STIM_ITEMS.
extern const uint16_t STIM_LEAD_GAP_SAMP[N_STIM_ITEMS];

