// GENERATED by fakefish-gen-constants from shared/stim_constants.json — DO NOT EDIT.
//
// Playback / session constants shared by the fakefish surfaces. Edit
// shared/stim_constants.json and re-run `uv run fakefish-gen-constants`.
//
// The SAMPLE RATE is not defined here — it comes from eel_stimuli.h
// (STIM_SAMPLE_RATE_HZ), so it is stated exactly once in the whole repo. Every
// sample-unit figure below is derived from it by the preprocessor.
//
// BOTH DEVICES MARK WITH EEL PULSES, but with DIFFERENT codes — not unified:
//   SD_MARKER_*    6 pulses at a fixed 10 Hz with ALTERNATING polarity, baked into
//                  the WAV card by build_sd_card.py. Identifies a playback.
//   PULSE_MARKER_* 2 or 4 pulses at a fixed 100 Hz, SAME polarity, synthesised live
//                  by the RC device. The COUNT tags volley vs sham.
#pragma once
#include <stdint.h>
#include "eel_stimuli.h"   // STIM_SAMPLE_RATE_HZ — the one place the rate is defined

// ===== SD path — levels baked into the WAV card ============================
// Absolute output levels as a fraction of full scale (NOT peak-normalised): the
// loc/volley/marker ratios are the experiment, so they must survive rendering.
#define SD_LEVEL_VOLLEY       0.9f
#define SD_LEVEL_LOC          0.225f
#define SD_LEVEL_CALIBRATION  0.45f
#define SD_LEVEL_MARKER       0.5f

// ===== SD path — the alternating-polarity pulse marker =====================
// The lead-in that identifies a playback: SD_MARKER_N_PULSES EOD pulses at a fixed
// IPI, with the polarity ALTERNATING pulse to pulse. Alternation is the discriminator
// (no eel alternates; a localization train is single-polarity) and it survives the
// firmware's per-press random polarity flip, which negates the whole WAV. The pulse
// count is EVEN so the burst carries no net charge.
#define SD_MARKER_N_PULSES    6
#define SD_MARKER_RATE_HZ     10.0f
#define SD_MARKER_IPI_SAMP    5000u   // 100 ms
#define SD_MARKER_SAMP        ((uint32_t)SD_MARKER_IPI_SAMP * (SD_MARKER_N_PULSES - 1) + EOD_HV_LEN)

// ===== SD path — program A, the calibration train ==========================
// A steady SINGLE-polarity EOD train at a known rate and level: a plain reference
// signal, deliberately not a code.
#define SD_CAL_RATE_HZ        50.0f
#define SD_CAL_IPI_SAMP       1000u
#define SD_CAL_S              10
#define SD_CAL_SAMP           ((uint32_t)SD_CAL_S * STIM_SAMPLE_RATE_HZ)

// ===== SD path — session structure =========================================
// Seconds are the authored unit; sample units are derived from STIM_SAMPLE_RATE_HZ.
#define SD_SESSION_LOC_S         20   // localization window (program B)
#define SD_SESSION_D_LOC_S       5    // localization lead (program D)
#define SD_SESSION_D_GAP_MS      300  // loc -> volley gap (program D)
#define SD_SESSION_LOC_SAMP      ((uint32_t)SD_SESSION_LOC_S    * STIM_SAMPLE_RATE_HZ)
#define SD_SESSION_D_LOC_SAMP    ((uint32_t)SD_SESSION_D_LOC_S  * STIM_SAMPLE_RATE_HZ)
#define SD_SESSION_D_GAP_SAMP    ((uint32_t)SD_SESSION_D_GAP_MS * STIM_SAMPLE_RATE_HZ / 1000u)

// Nominal open-circuit pulse peak at full scale. NOT a calibrated field strength —
// in water the source impedance divides against the load. Operator-set nominal only.
#define SD_FULLSCALE_PULSE_PEAK_MV 3313.0f

// ===== RC path — the coded pulse-burst marker ==============================
// A short EOD burst at a fixed IPI, tagged by PULSE COUNT: volley vs sham.
#define PULSE_MARKER_IPI_SAMP      500u   // 500 samp @ 50 kHz == 10 ms == 100 Hz
#define PULSE_MARKER_PULSES_VOLLEY 2u
#define PULSE_MARKER_PULSES_SHAM   4u
#define PULSE_MARKER_MAX_PULSES    8u   // sizes the static marker IPI table
#define PULSE_MARKER_AMP           0.5f // fixed, independent of the amplitude control

// ===== RC path — blinded trial draw ========================================
// The RC trigger fires in ONE direction and does not say WHICH trial to run; the
// firmware draws volley-vs-sham at playback time, so the operator cannot choose and
// their timing cannot correlate with the trial type. The draw happens in the sample-
// clock ISR, never in loop(), because random() must stay single-caller.
#define TRIAL_P_VOLLEY      0.5f // P(volley); the rest are shams
#define TRIAL_DRAW_RANGE    10000   // draw random(TRIAL_DRAW_RANGE)...
#define TRIAL_VOLLEY_CUTOFF ((long)(TRIAL_P_VOLLEY * (float)TRIAL_DRAW_RANGE))  // ...< this = volley

// ===== RC path — amplitude =================================================
// The control sets the VOLLEY (max); localization is DERIVED as volley / ratio.
#define VOLLEY_AMP_RATIO   4.0f
#define MASTER_AMP_MIN     0.0f
#define MASTER_AMP_MAX     1.0f
#define PANEL_VOLLEY_AMP   1.0f // bench default (no transmitter)

// ===== RC path — live localization train ===================================
// The RHYTHM is the fitted model (loc_model_params.h + loc_rhythm.h); these are only
// the ranges the operator's knobs span.
//
// CH3 is a TICK TEMPO — one over the median interval — not an average pulse rate. The
// measured eel ticks at LOC_NOMINAL_TICK_HZ (3.15 Hz). Under the retired lognormal a
// setting of 5 Hz meant 5 pulses/s on average; it now means the fish ticks at 5 Hz,
// which delivers about 3.3 pulses/s once the heavy tail is included.
#define LOC_RATE_MIN_HZ    1.0f
#define LOC_RATE_MAX_HZ    20.0f
#define PANEL_RATE_HZ      5.0f
// CH5 bench default. 1.0 IS the measured eel (0 = metronome, useful to ~1.5). This is
// NOT the retired jitter CV: it scales the state score, so it changes how MUCH the rate
// varies without touching how it varies over time.
#define PANEL_RANDOMNESS   1.0f
// Minimum IPI. MUST stay > EOD_HV_LEN so localization pulses can never overlap —
// that invariant is what lets locgen.h use a single-pulse scheduler.
//
// This is the RESTING/VOLLEY ANTIMODE, not an arbitrary margin. The model's interval
// table is clamped to it in SCORE space, but rate is a pure TIME dilation, so any
// tick tempo above the nominal 3.15 Hz scales that floor down with everything else
// (4.4 ms at CH3 = 20 Hz). Since the source analysis separates resting pulses from
// fast runs on exactly this antimode, an unfloored fast train would emit intervals
// that read as micro-bursts of our own making.
#define LOC_REFRACTORY_SAMP 1250u  // 25 ms @ 50 kHz
