// GENERATED by fakefish-gen-constants from shared/stim_constants.json — DO NOT EDIT.
//
// Playback / session constants shared by the fakefish surfaces. Edit
// shared/stim_constants.json and re-run `uv run fakefish-gen-constants`.
//
// The SAMPLE RATE is not defined here — it comes from eel_stimuli.h
// (STIM_SAMPLE_RATE_HZ), so it is stated exactly once in the whole repo. Every
// sample-unit figure below is derived from it by the preprocessor.
//
// TWO DIFFERENT MARKERS, deliberately NOT unified:
//   SD_MARKER_*    a 10 kHz SINE TONE, baked into the WAV card by build_sd_card.py
//                  and played by the 6-button SD device.
//   PULSE_MARKER_* a coded EOD PULSE BURST, synthesised live by the RC device and
//                  tagged by pulse count (volley vs sham).
#pragma once
#include <stdint.h>
#include "eel_stimuli.h"   // STIM_SAMPLE_RATE_HZ — the one place the rate is defined

// ===== SD path — levels baked into the WAV card ============================
// Absolute output levels as a fraction of full scale (NOT peak-normalised): the
// loc/volley/marker ratios are the experiment, so they must survive rendering.
#define SD_LEVEL_VOLLEY          0.9f
#define SD_LEVEL_LOC             0.45f
#define SD_LEVEL_SINE_MARKER     0.25f
#define SD_LEVEL_SINE_MARKER_CAL 0.25f

// ===== SD path — the 10 kHz sine marker ====================================
// One exact cycle at SD_MARKER_FREQ_HZ. The LUT is DERIVED at codegen from
// round(32767 * sin(2*pi*k/n)), n = rate/freq; it sums to exactly 0 so the
// tone puts no net charge on the (DC-uncoupled) electrodes.
#define SD_MARKER_FREQ_HZ        10000
#define SD_MARKER_RAMP_SAMPLES   100   // raised-cosine on/off ramp (anti-click)
#define SD_MARKER_LUT_LEN        (STIM_SAMPLE_RATE_HZ / SD_MARKER_FREQ_HZ)
static const int16_t SD_MARKER_LUT[5] = { 0, 31163, 19260, -19260, -31163 };

// ===== SD path — session structure =========================================
// Seconds are the authored unit; sample units are derived from STIM_SAMPLE_RATE_HZ.
#define SD_SESSION_LEADIN_S      1    // pre-stimulus lead-in tone (B/C/D)
#define SD_SESSION_CAL_S         10   // calibration tone (program A)
#define SD_SESSION_LOC_S         20   // localization window (program B)
#define SD_SESSION_D_LOC_S       5    // localization lead (program D)
#define SD_SESSION_D_GAP_MS      300  // loc -> volley gap (program D)
#define SD_SESSION_LEADIN_SAMP   ((uint32_t)SD_SESSION_LEADIN_S * STIM_SAMPLE_RATE_HZ)
#define SD_SESSION_CAL_SAMP      ((uint32_t)SD_SESSION_CAL_S    * STIM_SAMPLE_RATE_HZ)
#define SD_SESSION_LOC_SAMP      ((uint32_t)SD_SESSION_LOC_S    * STIM_SAMPLE_RATE_HZ)
#define SD_SESSION_D_LOC_SAMP    ((uint32_t)SD_SESSION_D_LOC_S  * STIM_SAMPLE_RATE_HZ)
#define SD_SESSION_D_GAP_SAMP    ((uint32_t)SD_SESSION_D_GAP_MS * STIM_SAMPLE_RATE_HZ / 1000u)

// Nominal open-circuit pulse peak at full scale. NOT a calibrated field strength —
// in water the source impedance divides against the load. Operator-set nominal only.
#define SD_FULLSCALE_PULSE_PEAK_MV 3313.0f

// ===== RC path — the coded pulse-burst marker ==============================
// A short EOD burst at a fixed IPI, tagged by PULSE COUNT: volley vs sham.
#define PULSE_MARKER_IPI_SAMP      500u   // 500 samp @ 50 kHz == 10 ms == 100 Hz
#define PULSE_MARKER_PULSES_VOLLEY 2u
#define PULSE_MARKER_PULSES_SHAM   4u
#define PULSE_MARKER_MAX_PULSES    8u   // sizes the static marker IPI table
#define PULSE_MARKER_AMP           0.5f // fixed, independent of the amplitude control

// ===== RC path — amplitude =================================================
// The control sets the VOLLEY (max); localization is DERIVED as volley / ratio.
#define VOLLEY_AMP_RATIO   2.0f
#define MASTER_AMP_MIN     0.0f
#define MASTER_AMP_MAX     1.0f
#define PANEL_VOLLEY_AMP   1.0f // bench default (no transmitter)

// ===== RC path — live localization train ===================================
#define LOC_RATE_MIN_HZ    1.0f
#define LOC_RATE_MAX_HZ    20.0f
#define PANEL_RATE_HZ      5.0f
#define PANEL_CV           0.2f
// Minimum IPI. MUST stay > EOD_HV_LEN so localization pulses can never overlap —
// that invariant is what lets locgen.h use a single-pulse scheduler.
#define LOC_REFRACTORY_SAMP 250u  // 5 ms @ 50 kHz
