"""GENERATED by fakefish-gen-constants from shared/stim_constants.json — DO NOT EDIT.

Playback/session constants for the SD-card path, generated from
``shared/stim_constants.json``. ``build_sd_card.py`` bakes these into the WAV card
and ``_gallery_marker.py`` draws the galleries at the same levels, so the figures
and the card can no longer drift apart.

The sample rate is NOT restated here — it is imported from the export tool, which
is where it is defined once for the whole repo.
"""

from __future__ import annotations

from fakefish.export_teensy_stimuli import PLAYBACK_RATE_HZ as RATE_HZ

# ===== Absolute output levels (fraction of full scale) ==============================
VOLLEY_AMPLITUDE = 0.9
LOC_AMPLITUDE = 0.225
CAL_AMPLITUDE = 0.45
MARKER_AMPLITUDE = 0.5

# ===== The alternating-polarity pulse marker (the lead-in) ==========================
#: EVEN by construction, so the burst is charge-balanced; alternation is what
#: identifies it, and alternation survives the firmware's per-press polarity flip.
MARKER_N_PULSES = 6
MARKER_RATE_HZ = 10.0
MARKER_IPI_SAMPLES = 5000
#: First onset to last onset (the burst's span, excluding the final pulse's tail).
MARKER_SPAN_SAMPLES = 25000
MARKER_SPAN_S = 0.5

# ===== Program A: the calibration train =============================================
CAL_RATE_HZ = 50.0
CAL_IPI_SAMPLES = 1000
CAL_S = 10.0
CAL_SAMPLES = 10 * RATE_HZ

# ===== Session structure ============================================================
LOC_PLAYBACK_S = 20.0
D_LOC_PLAYBACK_S = 5.0
D_INTERPHASE_GAP_S = 0.3

LOC_PLAYBACK_SAMPLES = 20 * RATE_HZ
D_LOC_PLAYBACK_SAMPLES = 5 * RATE_HZ
D_INTERPHASE_GAP_SAMPLES = 300 * RATE_HZ // 1000

# ===== Nominal mV map ===============================================================
#: Nominal OPEN-CIRCUIT pulse peak at full scale, not a calibrated field strength.
FULLSCALE_PULSE_PEAK_MV = 3313.0
