"""GENERATED by fakefish-gen-constants from shared/stim_constants.json — DO NOT EDIT.

Playback/session constants for the SD-card path, generated from
``shared/stim_constants.json``. ``build_sd_card.py`` bakes these into the WAV card
and ``_gallery_marker.py`` draws the galleries at the same levels, so the figures
and the card can no longer drift apart.

The sample rate is NOT restated here — it is imported from the export tool, which
is where it is defined once for the whole repo.
"""

from __future__ import annotations

import numpy as np

from fakefish.export_teensy_stimuli import PLAYBACK_RATE_HZ as RATE_HZ

# ===== Absolute output levels (fraction of full scale) ==============================
VOLLEY_AMPLITUDE = 0.9
LOC_AMPLITUDE = 0.45
MARKER_AMPLITUDE = 0.25
MARKER_CAL_AMPLITUDE = 0.25

# ===== The 10 kHz sine marker =======================================================
MARKER_FREQ_HZ = 10000
MARKER_RAMP_SAMPLES = 100
#: One exact cycle, derived at codegen from
#: round(32767 * sin(2*pi*k/n)), n = RATE_HZ / MARKER_FREQ_HZ. Sums to exactly 0.
MARKER_LUT = np.array([0, 31163, 19260, -19260, -31163], dtype=np.float64)

# ===== Session structure ============================================================
MARKER_LEADIN_S = 1.0
MARKER_CAL_S = 10.0
LOC_PLAYBACK_S = 20.0
D_LOC_PLAYBACK_S = 5.0
D_INTERPHASE_GAP_S = 0.3

MARKER_LEADIN_SAMPLES = 1 * RATE_HZ
MARKER_CAL_SAMPLES = 10 * RATE_HZ
LOC_PLAYBACK_SAMPLES = 20 * RATE_HZ
D_LOC_PLAYBACK_SAMPLES = 5 * RATE_HZ
D_INTERPHASE_GAP_SAMPLES = 300 * RATE_HZ // 1000

# ===== Nominal mV map ===============================================================
#: Nominal OPEN-CIRCUIT pulse peak at full scale, not a calibrated field strength.
FULLSCALE_PULSE_PEAK_MV = 3313.0
