"""Generate the shared playback constants for BOTH languages from one JSON file.

``shared/stim_constants.json`` is the single source of truth for the fakefish
playback/session constants. This tool renders it into:

* ``firmware/eel_core/stim_levels.h`` — ``#define``\\ s the sketches consume.
* ``src/fakefish/_constants.py`` — module constants the Python toolchain consumes.

Neither generated file may be hand-edited: ``fakefish-gen-constants`` overwrites both,
and a pytest guard (``tests/test_gen_constants.py``) fails if regenerating produces a
diff. That guard is what makes the JSON authoritative rather than merely aspirational.

**Why codegen when each group has one consumer today.** The SD-card path's levels and
timings live in Python (``build_sd_card.py`` bakes them into the WAVs) while the RC
path's live-synthesis constants live in C — two languages, two files, no shared
definition. Consolidating them here removes the drift hazard, makes the *pair* of
devices legible in one place, and means a future surface that renders SD-style sessions
live on-device already has the constants in C.

**The sample rate is deliberately NOT in the JSON.** It stays single-sourced in the
export-generated ``eel_stimuli.h`` (``STIM_SAMPLE_RATE_HZ``) and
``export_teensy_stimuli.PLAYBACK_RATE_HZ``. Every sample-unit figure below is *derived*
from it — in C by the preprocessor, in Python at import — so the rate is stated once.

**The two markers are different mechanisms** and are emitted under distinct prefixes
(``SD_MARKER_*`` = the 10 kHz sine tone baked into the WAVs; ``PULSE_MARKER_*`` = the RC
device's live coded pulse burst). Do not unify them.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import typer

from fakefish import _resources as _res
from fakefish.export_teensy_stimuli import PLAYBACK_RATE_HZ as RATE_HZ
from fakefish.viz.loggers import configure_logging, get_logger

log = get_logger(__name__)
app = typer.Typer(add_completion=False, help="Generate stim_levels.h + _constants.py from shared/stim_constants.json.")

#: The single source of truth.
SOURCE_JSON: Path = _res.ROOT / "shared" / "stim_constants.json"

#: The two generated outputs.
OUT_HEADER: Path = _res.ROOT / "firmware" / "eel_core" / "stim_levels.h"
OUT_PYTHON: Path = _res.ROOT / "src" / "fakefish" / "_constants.py"

#: Full-scale int16 amplitude used to synthesise the sine-marker LUT. Load-bearing:
#: 32640 and 32768 both yield a different LUT than the one the frozen library shipped with.
LUT_FULLSCALE = 32767

_BANNER = "GENERATED by fakefish-gen-constants from shared/stim_constants.json — DO NOT EDIT."


def _strip_comments(node: Any) -> Any:
    """Drop ``_comment`` keys recursively (JSON has no comment syntax; we fake it)."""
    if isinstance(node, dict):
        return {k: _strip_comments(v) for k, v in node.items() if k != "_comment"}
    if isinstance(node, list):
        return [_strip_comments(v) for v in node]
    return node


def load_constants(path: Path = SOURCE_JSON) -> dict:
    """Read + validate the source JSON, returning it with ``_comment`` keys stripped."""
    raw = json.loads(path.read_text())
    return _strip_comments(raw)


def marker_lut(freq_hz: int, rate_hz: int) -> list[int]:
    """The sine-marker LUT: one exact cycle at ``freq_hz``, as clamped ``int16``.

    ``lut[k] = round(LUT_FULLSCALE * sin(2*pi*k/n))`` for ``n = rate_hz / freq_hz``
    samples per cycle. Python's banker's rounding is not a hazard here — no product
    lands on a .5 boundary — but we round half away from zero anyway so the result is
    rounding-mode independent and symmetric about zero.
    """
    n = rate_hz // freq_hz
    out = []
    for k in range(n):
        v = LUT_FULLSCALE * math.sin(2.0 * math.pi * k / n)
        out.append(int(math.floor(v + 0.5)) if v >= 0 else -int(math.floor(-v + 0.5)))
    return out


def validate(c: dict, rate_hz: int) -> None:
    """Fail loudly on a JSON edit that would break a load-bearing playback invariant."""
    sd = c["sd_path"]
    freq = sd["sine_marker"]["freq_hz"]

    # (1) Whole samples per marker cycle. Otherwise the LUT is not one exact cycle and
    #     the tone develops a DC offset and spectral splatter.
    if rate_hz % freq != 0:
        raise ValueError(
            f"sample rate {rate_hz} Hz is not an integer multiple of the marker "
            f"frequency {freq} Hz — the marker LUT would not be a whole cycle"
        )

    # (2) The LUT must sum to exactly zero: the electrodes carry no DC-blocking cap, so a
    #     tone with net charge would electrolyse/pit them over a long calibration hold.
    lut = marker_lut(freq, rate_hz)
    if sum(lut) != 0:
        raise ValueError(f"marker LUT does not sum to zero (got {sum(lut)}): net DC on the electrodes")

    # (3) Every tone must be a whole number of cycles, for the same reason.
    per_cycle = rate_hz // freq
    tones = {
        "leadin_s": sd["session"]["leadin_s"] * rate_hz,
        "cal_s": sd["session"]["cal_s"] * rate_hz,
    }
    for name, total in tones.items():
        if total % per_cycle != 0:
            raise ValueError(
                f"{name} ({total} samples) is not a whole number of {per_cycle}-sample "
                f"marker cycles — the tone would end mid-cycle with net DC"
            )

    # (4) Levels are fractions of full scale.
    for name, v in sd["levels"].items():
        if not 0.0 <= v <= 1.0:
            raise ValueError(f"sd_path.levels.{name} = {v} is outside 0..1 (fraction of full scale)")

    # (5) Localization is derived as volley / ratio, so the ratio must not be zero.
    if c["rc_path"]["amp"]["volley_amp_ratio"] <= 0.0:
        raise ValueError("rc_path.amp.volley_amp_ratio must be > 0 (localization = volley / ratio)")

    # (6) The marker IPI table is sized by max_pulses; both tags must fit.
    pm = c["rc_path"]["pulse_marker"]
    if max(pm["pulses_volley"], pm["pulses_sham"]) > pm["max_pulses"]:
        raise ValueError("rc_path.pulse_marker.max_pulses is smaller than a tag it must hold")


def _f(x: float) -> str:
    """Render a float as a C float literal, stably (``0.9`` -> ``0.90f``)."""
    return f"{x!r}f" if "." in repr(x) else f"{float(x)!r}f"


def render_header(c: dict) -> str:
    """Render ``firmware/eel_core/stim_levels.h``."""
    sd, rc = c["sd_path"], c["rc_path"]
    freq = sd["sine_marker"]["freq_hz"]
    lut = marker_lut(freq, RATE_HZ)
    lvl, ses = sd["levels"], sd["session"]
    pm, amp, loc = rc["pulse_marker"], rc["amp"], rc["loc_rate"]

    lut_body = ", ".join(str(v) for v in lut)
    L = []
    a = L.append
    a(f"// {_BANNER}")
    a("//")
    a("// Playback / session constants shared by the fakefish surfaces. Edit")
    a("// shared/stim_constants.json and re-run `uv run fakefish-gen-constants`.")
    a("//")
    a("// The SAMPLE RATE is not defined here — it comes from eel_stimuli.h")
    a("// (STIM_SAMPLE_RATE_HZ), so it is stated exactly once in the whole repo. Every")
    a("// sample-unit figure below is derived from it by the preprocessor.")
    a("//")
    a("// TWO DIFFERENT MARKERS, deliberately NOT unified:")
    a("//   SD_MARKER_*    a 10 kHz SINE TONE, baked into the WAV card by build_sd_card.py")
    a("//                  and played by the 6-button SD device.")
    a("//   PULSE_MARKER_* a coded EOD PULSE BURST, synthesised live by the RC device and")
    a("//                  tagged by pulse count (volley vs sham).")
    a("#pragma once")
    a('#include <stdint.h>')
    a('#include "eel_stimuli.h"   // STIM_SAMPLE_RATE_HZ — the one place the rate is defined')
    a("")
    a("// ===== SD path — levels baked into the WAV card ============================")
    a("// Absolute output levels as a fraction of full scale (NOT peak-normalised): the")
    a("// loc/volley/marker ratios are the experiment, so they must survive rendering.")
    a(f"#define SD_LEVEL_VOLLEY          {_f(lvl['volley'])}")
    a(f"#define SD_LEVEL_LOC             {_f(lvl['loc'])}")
    a(f"#define SD_LEVEL_SINE_MARKER     {_f(lvl['sine_marker'])}")
    a(f"#define SD_LEVEL_SINE_MARKER_CAL {_f(lvl['sine_marker_cal'])}")
    a("")
    a("// ===== SD path — the 10 kHz sine marker ====================================")
    a("// One exact cycle at SD_MARKER_FREQ_HZ. The LUT is DERIVED at codegen from")
    a(f"// round({LUT_FULLSCALE} * sin(2*pi*k/n)), n = rate/freq; it sums to exactly 0 so the")
    a("// tone puts no net charge on the (DC-uncoupled) electrodes.")
    a(f"#define SD_MARKER_FREQ_HZ        {freq}")
    a(f"#define SD_MARKER_RAMP_SAMPLES   {sd['sine_marker']['ramp_samples']}   // raised-cosine on/off ramp (anti-click)")
    a("#define SD_MARKER_LUT_LEN        (STIM_SAMPLE_RATE_HZ / SD_MARKER_FREQ_HZ)")
    a(f"static const int16_t SD_MARKER_LUT[{len(lut)}] = {{ {lut_body} }};")
    a("")
    a("// ===== SD path — session structure =========================================")
    a("// Seconds are the authored unit; sample units are derived from STIM_SAMPLE_RATE_HZ.")
    a(f"#define SD_SESSION_LEADIN_S      {ses['leadin_s']}    // pre-stimulus lead-in tone (B/C/D)")
    a(f"#define SD_SESSION_CAL_S         {ses['cal_s']}   // calibration tone (program A)")
    a(f"#define SD_SESSION_LOC_S         {ses['loc_s']}   // localization window (program B)")
    a(f"#define SD_SESSION_D_LOC_S       {ses['d_loc_s']}    // localization lead (program D)")
    a(f"#define SD_SESSION_D_GAP_MS      {ses['d_gap_ms']}  // loc -> volley gap (program D)")
    a("#define SD_SESSION_LEADIN_SAMP   ((uint32_t)SD_SESSION_LEADIN_S * STIM_SAMPLE_RATE_HZ)")
    a("#define SD_SESSION_CAL_SAMP      ((uint32_t)SD_SESSION_CAL_S    * STIM_SAMPLE_RATE_HZ)")
    a("#define SD_SESSION_LOC_SAMP      ((uint32_t)SD_SESSION_LOC_S    * STIM_SAMPLE_RATE_HZ)")
    a("#define SD_SESSION_D_LOC_SAMP    ((uint32_t)SD_SESSION_D_LOC_S  * STIM_SAMPLE_RATE_HZ)")
    a("#define SD_SESSION_D_GAP_SAMP    ((uint32_t)SD_SESSION_D_GAP_MS * STIM_SAMPLE_RATE_HZ / 1000u)")
    a("")
    a("// Nominal open-circuit pulse peak at full scale. NOT a calibrated field strength —")
    a("// in water the source impedance divides against the load. Operator-set nominal only.")
    a(f"#define SD_FULLSCALE_PULSE_PEAK_MV {_f(sd['fullscale_pulse_peak_mv'])}")
    a("")
    a("// ===== RC path — the coded pulse-burst marker ==============================")
    a("// A short EOD burst at a fixed IPI, tagged by PULSE COUNT: volley vs sham.")
    a(f"#define PULSE_MARKER_IPI_SAMP      {pm['ipi_samp']}u   // {pm['ipi_samp']} samp @ 50 kHz == 10 ms == 100 Hz")
    a(f"#define PULSE_MARKER_PULSES_VOLLEY {pm['pulses_volley']}u")
    a(f"#define PULSE_MARKER_PULSES_SHAM   {pm['pulses_sham']}u")
    a(f"#define PULSE_MARKER_MAX_PULSES    {pm['max_pulses']}u   // sizes the static marker IPI table")
    a(f"#define PULSE_MARKER_AMP           {_f(pm['amp'])} // fixed, independent of the amplitude control")
    a("")
    a("// ===== RC path — amplitude =================================================")
    a("// The control sets the VOLLEY (max); localization is DERIVED as volley / ratio.")
    a(f"#define VOLLEY_AMP_RATIO   {_f(amp['volley_amp_ratio'])}")
    a(f"#define MASTER_AMP_MIN     {_f(amp['master_min'])}")
    a(f"#define MASTER_AMP_MAX     {_f(amp['master_max'])}")
    a(f"#define PANEL_VOLLEY_AMP   {_f(amp['panel_volley_amp'])} // bench default (no transmitter)")
    a("")
    a("// ===== RC path — live localization train ===================================")
    a(f"#define LOC_RATE_MIN_HZ    {_f(loc['min_hz'])}")
    a(f"#define LOC_RATE_MAX_HZ    {_f(loc['max_hz'])}")
    a(f"#define PANEL_RATE_HZ      {_f(loc['panel_rate_hz'])}")
    a(f"#define PANEL_CV           {_f(loc['panel_cv'])}")
    a("// Minimum IPI. MUST stay > EOD_HV_LEN so localization pulses can never overlap —")
    a("// that invariant is what lets locgen.h use a single-pulse scheduler.")
    a(f"#define LOC_REFRACTORY_SAMP {loc['refractory_samp']}u  // 5 ms @ 50 kHz")
    a("")
    return "\n".join(L)


def render_python(c: dict) -> str:
    """Render ``src/fakefish/_constants.py`` (the SD-path group the toolchain consumes)."""
    sd = c["sd_path"]
    freq = sd["sine_marker"]["freq_hz"]
    lut = marker_lut(freq, RATE_HZ)
    lvl, ses = sd["levels"], sd["session"]

    L = []
    a = L.append
    a(f'"""{_BANNER}')
    a("")
    a("Playback/session constants for the SD-card path, generated from")
    a("``shared/stim_constants.json``. ``build_sd_card.py`` bakes these into the WAV card")
    a("and ``_gallery_marker.py`` draws the galleries at the same levels, so the figures")
    a("and the card can no longer drift apart.")
    a("")
    a("The sample rate is NOT restated here — it is imported from the export tool, which")
    a("is where it is defined once for the whole repo.")
    a('"""')
    a("")
    a("from __future__ import annotations")
    a("")
    a("import numpy as np")
    a("")
    a("from fakefish.export_teensy_stimuli import PLAYBACK_RATE_HZ as RATE_HZ")
    a("")
    a("# ===== Absolute output levels (fraction of full scale) ==============================")
    a(f"VOLLEY_AMPLITUDE = {lvl['volley']!r}")
    a(f"LOC_AMPLITUDE = {lvl['loc']!r}")
    a(f"MARKER_AMPLITUDE = {lvl['sine_marker']!r}")
    a(f"MARKER_CAL_AMPLITUDE = {lvl['sine_marker_cal']!r}")
    a("")
    a("# ===== The 10 kHz sine marker =======================================================")
    a(f"MARKER_FREQ_HZ = {freq!r}")
    a(f"MARKER_RAMP_SAMPLES = {sd['sine_marker']['ramp_samples']!r}")
    a("#: One exact cycle, derived at codegen from")
    a(f"#: round({LUT_FULLSCALE} * sin(2*pi*k/n)), n = RATE_HZ / MARKER_FREQ_HZ. Sums to exactly 0.")
    a(f"MARKER_LUT = np.array({lut!r}, dtype=np.float64)")
    a("")
    a("# ===== Session structure ============================================================")
    a(f"MARKER_LEADIN_S = {float(ses['leadin_s'])!r}")
    a(f"MARKER_CAL_S = {float(ses['cal_s'])!r}")
    a(f"LOC_PLAYBACK_S = {float(ses['loc_s'])!r}")
    a(f"D_LOC_PLAYBACK_S = {float(ses['d_loc_s'])!r}")
    a(f"D_INTERPHASE_GAP_S = {ses['d_gap_ms'] / 1000.0!r}")
    a("")
    a(f"MARKER_LEADIN_SAMPLES = {ses['leadin_s']} * RATE_HZ")
    a(f"MARKER_CAL_SAMPLES = {ses['cal_s']} * RATE_HZ")
    a(f"LOC_PLAYBACK_SAMPLES = {ses['loc_s']} * RATE_HZ")
    a(f"D_LOC_PLAYBACK_SAMPLES = {ses['d_loc_s']} * RATE_HZ")
    a(f"D_INTERPHASE_GAP_SAMPLES = {ses['d_gap_ms']} * RATE_HZ // 1000")
    a("")
    a("# ===== Nominal mV map ===============================================================")
    a("#: Nominal OPEN-CIRCUIT pulse peak at full scale, not a calibrated field strength.")
    a(f"FULLSCALE_PULSE_PEAK_MV = {sd['fullscale_pulse_peak_mv']!r}")
    a("")
    return "\n".join(L)


def generate(source: Path = SOURCE_JSON) -> dict[Path, str]:
    """Render both outputs. Returns ``{path: content}`` without writing anything."""
    c = load_constants(source)
    validate(c, RATE_HZ)
    return {OUT_HEADER: render_header(c), OUT_PYTHON: render_python(c)}


@app.command()
def main(
    check: bool = typer.Option(
        False, "--check", help="Do not write; exit non-zero if a generated file is stale."
    ),
    verbose: int = typer.Option(0, "--verbose", "-v", count=True, help="-v INFO, -vv DEBUG."),
) -> None:
    """Regenerate ``stim_levels.h`` + ``_constants.py`` from ``shared/stim_constants.json``."""
    configure_logging(verbose)
    rendered = generate()

    stale = []
    for path, content in rendered.items():
        current = path.read_text() if path.exists() else None
        if current == content:
            log.info("up to date: %s", path)
            continue
        stale.append(path)
        if check:
            log.error("STALE: %s", path)
        else:
            path.write_text(content)
            log.info("wrote %s", path)

    if check:
        if stale:
            names = ", ".join(str(p) for p in stale)
            typer.echo(
                f"STALE (re-run fakefish-gen-constants and commit): {names}", err=True
            )
            raise typer.Exit(code=1)
        typer.echo(f"up to date: {len(rendered)} generated file(s)")
        return
    typer.echo(f"generated {len(rendered)} file(s) from {SOURCE_JSON.name}")


if __name__ == "__main__":
    app()
