"""Generate the shared playback constants for BOTH languages from one JSON file.

``shared/stim_constants.json`` is the single source of truth for the fakefish
playback/session constants. This tool renders it into:

* ``firmware/eel_core/stim_levels.h`` — ``#define``\\ s the sketches consume.
* ``src/fakefish/_constants.py`` — module constants the Python toolchain consumes.

Neither generated file may be hand-edited: ``fakefish-gen-constants`` overwrites both,
and a pytest guard (``tests/test_gen_constants.py``) fails if regenerating produces a
diff. That guard is what makes the JSON authoritative rather than merely aspirational.

**Why codegen when each group has one consumer today.** The SD-card path's levels and
timings live in Python (``build_sd_card.py`` bakes them into the WAVs) while the RC
path's live-synthesis constants live in C — two languages, two files, no shared
definition. Consolidating them here removes the drift hazard, makes the *pair* of
devices legible in one place, and means a future surface that renders SD-style sessions
live on-device already has the constants in C.

**The sample rate is deliberately NOT in the JSON.** It stays single-sourced in the
export-generated ``eel_stimuli.h`` (``STIM_SAMPLE_RATE_HZ``) and
``export_teensy_stimuli.PLAYBACK_RATE_HZ``. Every sample-unit figure below is *derived*
from it — in C by the preprocessor, in Python at import — so the rate is stated once.

**The two markers are different mechanisms** and are emitted under distinct prefixes
(``SD_MARKER_*`` = the SD card's 6-pulse alternating-polarity lead-in; ``PULSE_MARKER_*``
= the RC device's count-coded 100 Hz burst). Both are made of eel pulses now, but they
encode different things. Do not unify them.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import typer

from fakefish import _resources as _res
from fakefish.export_teensy_stimuli import PLAYBACK_RATE_HZ as RATE_HZ
from fakefish.viz.loggers import configure_logging, get_logger

log = get_logger(__name__)
app = typer.Typer(add_completion=False, help="Generate stim_levels.h + _constants.py from shared/stim_constants.json.")

#: The single source of truth.
SOURCE_JSON: Path = _res.ROOT / "shared" / "stim_constants.json"

#: The two generated outputs.
OUT_HEADER: Path = _res.ROOT / "firmware" / "eel_core" / "stim_levels.h"
OUT_PYTHON: Path = _res.ROOT / "src" / "fakefish" / "_constants.py"

_BANNER = "GENERATED by fakefish-gen-constants from shared/stim_constants.json — DO NOT EDIT."


def _strip_comments(node: Any) -> Any:
    """Drop ``_comment`` keys recursively (JSON has no comment syntax; we fake it)."""
    if isinstance(node, dict):
        return {k: _strip_comments(v) for k, v in node.items() if k != "_comment"}
    if isinstance(node, list):
        return [_strip_comments(v) for v in node]
    return node


def load_constants(path: Path = SOURCE_JSON) -> dict:
    """Read + validate the source JSON, returning it with ``_comment`` keys stripped."""
    raw = json.loads(path.read_text())
    return _strip_comments(raw)


def ipi_samples(rate_hz: float, sample_rate_hz: int) -> int:
    """Inter-pulse interval in whole samples for a pulse rate."""
    return int(round(sample_rate_hz / rate_hz))


def _eod_hv_len() -> int | None:
    """``EOD_HV_LEN`` from the generated library, so the no-overlap check uses the real EOD.

    Returns ``None`` if the header cannot be read (the check is then skipped rather than
    guessing a length).
    """
    header = OUT_HEADER.parent / "eel_stimuli.h"
    try:
        text = header.read_text()
    except OSError:
        return None
    for line in text.splitlines():
        if line.startswith("#define EOD_HV_LEN"):
            return int(line.split()[2])
    return None


def validate(c: dict, rate_hz: int, eod_len: int | None = None) -> None:
    """Fail loudly on a JSON edit that would break a load-bearing playback invariant."""
    sd = c["sd_path"]
    pm = sd["pulse_marker"]
    cal = sd["calibration"]

    # (1) The marker burst must be CHARGE-BALANCED. Alternating polarity cancels only if
    #     the pulse count is even; an odd count leaves one whole EOD of net charge on
    #     electrodes that have no DC-blocking capacitor. (This replaces the zero-sum
    #     property the retired sine LUT provided.)
    if pm["n_pulses"] % 2 != 0:
        raise ValueError(
            f"sd_path.pulse_marker.n_pulses = {pm['n_pulses']} is ODD — an alternating-polarity "
            f"burst only cancels its charge with an EVEN pulse count"
        )
    if pm["n_pulses"] < 2:
        raise ValueError("sd_path.pulse_marker.n_pulses must be at least 2 to alternate at all")

    # (2) Whole-sample intervals, so the burst is exactly periodic at any sample rate.
    for label, hz in (("pulse_marker.rate_hz", pm["rate_hz"]), ("calibration.rate_hz", cal["rate_hz"])):
        if abs(rate_hz / hz - round(rate_hz / hz)) > 1e-9:
            raise ValueError(
                f"sd_path.{label} = {hz} Hz does not divide the {rate_hz} Hz sample rate "
                f"into whole samples"
            )

    # (3) Marker pulses must not overlap: the burst is a sequence of DISCRETE pulses, and a
    #     rate fast enough to overlap them would blur the alternation that identifies it.
    if eod_len is not None:
        gap = ipi_samples(pm["rate_hz"], rate_hz)
        if gap <= eod_len:
            raise ValueError(
                f"sd_path.pulse_marker.rate_hz = {pm['rate_hz']} Hz gives a {gap}-sample IPI, "
                f"which is not longer than one EOD ({eod_len} samples) — marker pulses would overlap"
            )

    # (4) The marker must stay clear of the volley rate range (volleys peak at 300-400 Hz),
    #     or it stops being distinguishable from the stimulus it introduces.
    if pm["rate_hz"] > 100.0:
        raise ValueError(
            f"sd_path.pulse_marker.rate_hz = {pm['rate_hz']} Hz is inside the volley rate range; "
            f"keep the marker well below it"
        )

    # (5) Levels are fractions of full scale.
    for name, v in sd["levels"].items():
        if not 0.0 <= v <= 1.0:
            raise ValueError(f"sd_path.levels.{name} = {v} is outside 0..1 (fraction of full scale)")

    # (6) Localization is derived as volley / ratio, so the ratio must not be zero.
    if c["rc_path"]["amp"]["volley_amp_ratio"] <= 0.0:
        raise ValueError("rc_path.amp.volley_amp_ratio must be > 0 (localization = volley / ratio)")

    # (7) The RC marker IPI table is sized by max_pulses; both tags must fit.
    rcm = c["rc_path"]["pulse_marker"]
    if max(rcm["pulses_volley"], rcm["pulses_sham"]) > rcm["max_pulses"]:
        raise ValueError("rc_path.pulse_marker.max_pulses is smaller than a tag it must hold")


def _f(x: float) -> str:
    """Render a float as a C float literal, stably (``0.9`` -> ``0.90f``)."""
    return f"{x!r}f" if "." in repr(x) else f"{float(x)!r}f"


def render_header(c: dict) -> str:
    """Render ``firmware/eel_core/stim_levels.h``."""
    sd, rc = c["sd_path"], c["rc_path"]
    lvl, ses = sd["levels"], sd["session"]
    sdm, cal = sd["pulse_marker"], sd["calibration"]
    pm, amp, loc = rc["pulse_marker"], rc["amp"], rc["loc_rate"]

    L = []
    a = L.append
    a(f"// {_BANNER}")
    a("//")
    a("// Playback / session constants shared by the fakefish surfaces. Edit")
    a("// shared/stim_constants.json and re-run `uv run fakefish-gen-constants`.")
    a("//")
    a("// The SAMPLE RATE is not defined here — it comes from eel_stimuli.h")
    a("// (STIM_SAMPLE_RATE_HZ), so it is stated exactly once in the whole repo. Every")
    a("// sample-unit figure below is derived from it by the preprocessor.")
    a("//")
    a("// BOTH DEVICES MARK WITH EEL PULSES, but with DIFFERENT codes — not unified:")
    a("//   SD_MARKER_*    6 pulses at a fixed 10 Hz with ALTERNATING polarity, baked into")
    a("//                  the WAV card by build_sd_card.py. Identifies a playback.")
    a("//   PULSE_MARKER_* 2 or 4 pulses at a fixed 100 Hz, SAME polarity, synthesised live")
    a("//                  by the RC device. The COUNT tags volley vs sham.")
    a("#pragma once")
    a('#include <stdint.h>')
    a('#include "eel_stimuli.h"   // STIM_SAMPLE_RATE_HZ — the one place the rate is defined')
    a("")
    a("// ===== SD path — levels baked into the WAV card ============================")
    a("// Absolute output levels as a fraction of full scale (NOT peak-normalised): the")
    a("// loc/volley/marker ratios are the experiment, so they must survive rendering.")
    a(f"#define SD_LEVEL_VOLLEY       {_f(lvl['volley'])}")
    a(f"#define SD_LEVEL_LOC          {_f(lvl['loc'])}")
    a(f"#define SD_LEVEL_CALIBRATION  {_f(lvl['calibration'])}")
    a(f"#define SD_LEVEL_MARKER       {_f(lvl['pulse_marker'])}")
    a("")
    a("// ===== SD path — the alternating-polarity pulse marker =====================")
    a("// The lead-in that identifies a playback: SD_MARKER_N_PULSES EOD pulses at a fixed")
    a("// IPI, with the polarity ALTERNATING pulse to pulse. Alternation is the discriminator")
    a("// (no eel alternates; a localization train is single-polarity) and it survives the")
    a("// firmware's per-press random polarity flip, which negates the whole WAV. The pulse")
    a("// count is EVEN so the burst carries no net charge.")
    a(f"#define SD_MARKER_N_PULSES    {sdm['n_pulses']}")
    a(f"#define SD_MARKER_RATE_HZ     {_f(sdm['rate_hz'])}")
    a(f"#define SD_MARKER_IPI_SAMP    {ipi_samples(sdm['rate_hz'], RATE_HZ)}u   // {1000.0 / sdm['rate_hz']:.0f} ms")
    a("#define SD_MARKER_SAMP        ((uint32_t)SD_MARKER_IPI_SAMP * (SD_MARKER_N_PULSES - 1) + EOD_HV_LEN)")
    a("")
    a("// ===== SD path — program A, the calibration train ==========================")
    a("// A steady SINGLE-polarity EOD train at a known rate and level: a plain reference")
    a("// signal, deliberately not a code.")
    a(f"#define SD_CAL_RATE_HZ        {_f(cal['rate_hz'])}")
    a(f"#define SD_CAL_IPI_SAMP       {ipi_samples(cal['rate_hz'], RATE_HZ)}u")
    a(f"#define SD_CAL_S              {cal['duration_s']}")
    a("#define SD_CAL_SAMP           ((uint32_t)SD_CAL_S * STIM_SAMPLE_RATE_HZ)")
    a("")
    a("// ===== SD path — session structure =========================================")
    a("// Seconds are the authored unit; sample units are derived from STIM_SAMPLE_RATE_HZ.")
    a(f"#define SD_SESSION_LOC_S         {ses['loc_s']}   // localization window (program B)")
    a(f"#define SD_SESSION_D_LOC_S       {ses['d_loc_s']}    // localization lead (program D)")
    a(f"#define SD_SESSION_D_GAP_MS      {ses['d_gap_ms']}  // loc -> volley gap (program D)")
    a("#define SD_SESSION_LOC_SAMP      ((uint32_t)SD_SESSION_LOC_S    * STIM_SAMPLE_RATE_HZ)")
    a("#define SD_SESSION_D_LOC_SAMP    ((uint32_t)SD_SESSION_D_LOC_S  * STIM_SAMPLE_RATE_HZ)")
    a("#define SD_SESSION_D_GAP_SAMP    ((uint32_t)SD_SESSION_D_GAP_MS * STIM_SAMPLE_RATE_HZ / 1000u)")
    a("")
    a("// Nominal open-circuit pulse peak at full scale. NOT a calibrated field strength —")
    a("// in water the source impedance divides against the load. Operator-set nominal only.")
    a(f"#define SD_FULLSCALE_PULSE_PEAK_MV {_f(sd['fullscale_pulse_peak_mv'])}")
    a("")
    a("// ===== RC path — the coded pulse-burst marker ==============================")
    a("// A short EOD burst at a fixed IPI, tagged by PULSE COUNT: volley vs sham.")
    a(f"#define PULSE_MARKER_IPI_SAMP      {pm['ipi_samp']}u   // {pm['ipi_samp']} samp @ 50 kHz == 10 ms == 100 Hz")
    a(f"#define PULSE_MARKER_PULSES_VOLLEY {pm['pulses_volley']}u")
    a(f"#define PULSE_MARKER_PULSES_SHAM   {pm['pulses_sham']}u")
    a(f"#define PULSE_MARKER_MAX_PULSES    {pm['max_pulses']}u   // sizes the static marker IPI table")
    a(f"#define PULSE_MARKER_AMP           {_f(pm['amp'])} // fixed, independent of the amplitude control")
    a("")
    a("// ===== RC path — amplitude =================================================")
    a("// The control sets the VOLLEY (max); localization is DERIVED as volley / ratio.")
    a(f"#define VOLLEY_AMP_RATIO   {_f(amp['volley_amp_ratio'])}")
    a(f"#define MASTER_AMP_MIN     {_f(amp['master_min'])}")
    a(f"#define MASTER_AMP_MAX     {_f(amp['master_max'])}")
    a(f"#define PANEL_VOLLEY_AMP   {_f(amp['panel_volley_amp'])} // bench default (no transmitter)")
    a("")
    a("// ===== RC path — live localization train ===================================")
    a(f"#define LOC_RATE_MIN_HZ    {_f(loc['min_hz'])}")
    a(f"#define LOC_RATE_MAX_HZ    {_f(loc['max_hz'])}")
    a(f"#define PANEL_RATE_HZ      {_f(loc['panel_rate_hz'])}")
    a(f"#define PANEL_CV           {_f(loc['panel_cv'])}")
    a("// Minimum IPI. MUST stay > EOD_HV_LEN so localization pulses can never overlap —")
    a("// that invariant is what lets locgen.h use a single-pulse scheduler.")
    a(f"#define LOC_REFRACTORY_SAMP {loc['refractory_samp']}u  // 5 ms @ 50 kHz")
    a("")
    return "\n".join(L)


def render_python(c: dict) -> str:
    """Render ``src/fakefish/_constants.py`` (the SD-path group the toolchain consumes)."""
    sd = c["sd_path"]
    lvl, ses = sd["levels"], sd["session"]
    sdm, cal = sd["pulse_marker"], sd["calibration"]

    L = []
    a = L.append
    a(f'"""{_BANNER}')
    a("")
    a("Playback/session constants for the SD-card path, generated from")
    a("``shared/stim_constants.json``. ``build_sd_card.py`` bakes these into the WAV card")
    a("and ``_gallery_marker.py`` draws the galleries at the same levels, so the figures")
    a("and the card can no longer drift apart.")
    a("")
    a("The sample rate is NOT restated here — it is imported from the export tool, which")
    a("is where it is defined once for the whole repo.")
    a('"""')
    a("")
    a("from __future__ import annotations")
    a("")
    a("from fakefish.export_teensy_stimuli import PLAYBACK_RATE_HZ as RATE_HZ")
    a("")
    a("# ===== Absolute output levels (fraction of full scale) ==============================")
    a(f"VOLLEY_AMPLITUDE = {lvl['volley']!r}")
    a(f"LOC_AMPLITUDE = {lvl['loc']!r}")
    a(f"CAL_AMPLITUDE = {lvl['calibration']!r}")
    a(f"MARKER_AMPLITUDE = {lvl['pulse_marker']!r}")
    a("")
    a("# ===== The alternating-polarity pulse marker (the lead-in) ==========================")
    a("#: EVEN by construction, so the burst is charge-balanced; alternation is what")
    a("#: identifies it, and alternation survives the firmware's per-press polarity flip.")
    a(f"MARKER_N_PULSES = {sdm['n_pulses']!r}")
    a(f"MARKER_RATE_HZ = {sdm['rate_hz']!r}")
    a(f"MARKER_IPI_SAMPLES = {ipi_samples(sdm['rate_hz'], RATE_HZ)!r}")
    a("#: First onset to last onset (the burst's span, excluding the final pulse's tail).")
    a(f"MARKER_SPAN_SAMPLES = {ipi_samples(sdm['rate_hz'], RATE_HZ) * (sdm['n_pulses'] - 1)!r}")
    a(f"MARKER_SPAN_S = {ipi_samples(sdm['rate_hz'], RATE_HZ) * (sdm['n_pulses'] - 1) / RATE_HZ!r}")
    a("")
    a("# ===== Program A: the calibration train =============================================")
    a(f"CAL_RATE_HZ = {cal['rate_hz']!r}")
    a(f"CAL_IPI_SAMPLES = {ipi_samples(cal['rate_hz'], RATE_HZ)!r}")
    a(f"CAL_S = {float(cal['duration_s'])!r}")
    a(f"CAL_SAMPLES = {cal['duration_s']} * RATE_HZ")
    a("")
    a("# ===== Session structure ============================================================")
    a(f"LOC_PLAYBACK_S = {float(ses['loc_s'])!r}")
    a(f"D_LOC_PLAYBACK_S = {float(ses['d_loc_s'])!r}")
    a(f"D_INTERPHASE_GAP_S = {ses['d_gap_ms'] / 1000.0!r}")
    a("")
    a(f"LOC_PLAYBACK_SAMPLES = {ses['loc_s']} * RATE_HZ")
    a(f"D_LOC_PLAYBACK_SAMPLES = {ses['d_loc_s']} * RATE_HZ")
    a(f"D_INTERPHASE_GAP_SAMPLES = {ses['d_gap_ms']} * RATE_HZ // 1000")
    a("")
    a("# ===== Nominal mV map ===============================================================")
    a("#: Nominal OPEN-CIRCUIT pulse peak at full scale, not a calibrated field strength.")
    a(f"FULLSCALE_PULSE_PEAK_MV = {sd['fullscale_pulse_peak_mv']!r}")
    a("")
    return "\n".join(L)


def generate(source: Path = SOURCE_JSON) -> dict[Path, str]:
    """Render both outputs. Returns ``{path: content}`` without writing anything."""
    c = load_constants(source)
    validate(c, RATE_HZ, eod_len=_eod_hv_len())
    return {OUT_HEADER: render_header(c), OUT_PYTHON: render_python(c)}


@app.command()
def main(
    check: bool = typer.Option(
        False, "--check", help="Do not write; exit non-zero if a generated file is stale."
    ),
    verbose: int = typer.Option(0, "--verbose", "-v", count=True, help="-v INFO, -vv DEBUG."),
) -> None:
    """Regenerate ``stim_levels.h`` + ``_constants.py`` from ``shared/stim_constants.json``."""
    configure_logging(verbose)
    rendered = generate()

    stale = []
    for path, content in rendered.items():
        current = path.read_text() if path.exists() else None
        if current == content:
            log.info("up to date: %s", path)
            continue
        stale.append(path)
        if check:
            log.error("STALE: %s", path)
        else:
            path.write_text(content)
            log.info("wrote %s", path)

    if check:
        if stale:
            names = ", ".join(str(p) for p in stale)
            typer.echo(
                f"STALE (re-run fakefish-gen-constants and commit): {names}", err=True
            )
            raise typer.Exit(code=1)
        typer.echo(f"up to date: {len(rendered)} generated file(s)")
        return
    typer.echo(f"generated {len(rendered)} file(s) from {SOURCE_JSON.name}")


if __name__ == "__main__":
    app()
