"""Generate the shared playback constants for BOTH languages from JSON sources.

``shared/stim_constants.json`` is the single source of truth for the fakefish
playback/session constants. This tool renders it into:

* ``firmware/eel_core/stim_levels.h`` — ``#define``\\ s the sketches consume.
* ``src/fakefish/_constants.py`` — module constants the Python toolchain consumes.

A **second, independent** source is rendered here too, into C only:

* ``data/loc_model_params.json`` (vendored) -> ``firmware/eel_core/loc_model_params.h``
  — the fitted resting-rhythm model's tables, for ``loc_rhythm.h``.

Python does not need a generated copy of that one: ``fakefish.loc_model`` reads the JSON
directly, which is precisely what makes the C the only transcription and therefore the
only thing that can drift. See :func:`render_loc_header`.

None of the generated files may be hand-edited: ``fakefish-gen-constants`` overwrites all
three, and a pytest guard (``tests/test_gen_constants.py``) fails if regenerating produces
a diff. That guard is what makes the JSON authoritative rather than merely aspirational.

**Why codegen when each group has one consumer today.** The SD-card path's levels and
timings live in Python (``build_sd_card.py`` bakes them into the WAVs) while the RC
path's live-synthesis constants live in C — two languages, two files, no shared
definition. Consolidating them here removes the drift hazard, makes the *pair* of
devices legible in one place, and means a future surface that renders SD-style sessions
live on-device already has the constants in C.

**The sample rate is deliberately NOT in the JSON.** It stays single-sourced in the
export-generated ``eel_stimuli.h`` (``STIM_SAMPLE_RATE_HZ``) and
``export_teensy_stimuli.PLAYBACK_RATE_HZ``. Every sample-unit figure below is *derived*
from it — in C by the preprocessor, in Python at import — so the rate is stated once.

**There is one marker left, and only the SD device has it** (``SD_MARKER_*`` = the card's
6-pulse alternating-polarity lead-in). The RC device's count-coded 100 Hz burst was removed
on 2026-08-22: its per-pulse log cannot be absent, so the trial was already recorded, and
for a SHAM the burst was not redundant but a stimulus inside the no-stimulus control. The
SD device keeps its own because it writes no log at all.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import typer

from fakefish import _resources as _res
from fakefish.export_teensy_stimuli import PLAYBACK_RATE_HZ as RATE_HZ
from fakefish.viz.loggers import configure_logging, get_logger

log = get_logger(__name__)
app = typer.Typer(add_completion=False, help="Generate stim_levels.h + _constants.py from shared/stim_constants.json.")

#: The single source of truth for the authored playback/session constants.
SOURCE_JSON: Path = _res.ROOT / "shared" / "stim_constants.json"

#: The VENDORED fitted resting-rhythm model (copied from eeltracker, never edited here).
LOC_MODEL_JSON: Path = _res.DATA_DIR / "loc_model_params.json"

#: The three generated outputs.
OUT_HEADER: Path = _res.ROOT / "firmware" / "eel_core" / "stim_levels.h"
OUT_PYTHON: Path = _res.ROOT / "src" / "fakefish" / "_constants.py"
OUT_LOC_HEADER: Path = _res.ROOT / "firmware" / "eel_core" / "loc_model_params.h"

_BANNER = "GENERATED by fakefish-gen-constants from shared/stim_constants.json — DO NOT EDIT."
_LOC_BANNER = "GENERATED by fakefish-gen-constants from data/loc_model_params.json — DO NOT EDIT."


def _strip_comments(node: Any) -> Any:
    """Drop ``_comment`` keys recursively (JSON has no comment syntax; we fake it)."""
    if isinstance(node, dict):
        return {k: _strip_comments(v) for k, v in node.items() if k != "_comment"}
    if isinstance(node, list):
        return [_strip_comments(v) for v in node]
    return node


def load_constants(path: Path = SOURCE_JSON) -> dict:
    """Read + validate the source JSON, returning it with ``_comment`` keys stripped."""
    raw = json.loads(path.read_text())
    return _strip_comments(raw)


def ipi_samples(rate_hz: float, sample_rate_hz: int) -> int:
    """Inter-pulse interval in whole samples for a pulse rate."""
    return int(round(sample_rate_hz / rate_hz))


def _eod_hv_len() -> int | None:
    """``EOD_HV_LEN`` from the generated library, so the no-overlap check uses the real EOD.

    Returns ``None`` if the header cannot be read (the check is then skipped rather than
    guessing a length).
    """
    header = OUT_HEADER.parent / "eel_stimuli.h"
    try:
        text = header.read_text()
    except OSError:
        return None
    for line in text.splitlines():
        if line.startswith("#define EOD_HV_LEN"):
            return int(line.split()[2])
    return None


def validate(c: dict, rate_hz: int, eod_len: int | None = None) -> None:
    """Fail loudly on a JSON edit that would break a load-bearing playback invariant."""
    sd = c["sd_path"]
    pm = sd["pulse_marker"]
    cal = sd["calibration"]

    # (1) The marker burst must be CHARGE-BALANCED. Alternating polarity cancels only if
    #     the pulse count is even; an odd count leaves one whole EOD of net charge on
    #     electrodes that have no DC-blocking capacitor. (This replaces the zero-sum
    #     property the retired sine LUT provided.)
    if pm["n_pulses"] % 2 != 0:
        raise ValueError(
            f"sd_path.pulse_marker.n_pulses = {pm['n_pulses']} is ODD — an alternating-polarity "
            f"burst only cancels its charge with an EVEN pulse count"
        )
    if pm["n_pulses"] < 2:
        raise ValueError("sd_path.pulse_marker.n_pulses must be at least 2 to alternate at all")

    # (2) Whole-sample intervals, so the burst is exactly periodic at any sample rate.
    for label, hz in (("pulse_marker.rate_hz", pm["rate_hz"]), ("calibration.rate_hz", cal["rate_hz"])):
        if abs(rate_hz / hz - round(rate_hz / hz)) > 1e-9:
            raise ValueError(
                f"sd_path.{label} = {hz} Hz does not divide the {rate_hz} Hz sample rate "
                f"into whole samples"
            )

    # (3) Marker pulses must not overlap: the burst is a sequence of DISCRETE pulses, and a
    #     rate fast enough to overlap them would blur the alternation that identifies it.
    if eod_len is not None:
        gap = ipi_samples(pm["rate_hz"], rate_hz)
        if gap <= eod_len:
            raise ValueError(
                f"sd_path.pulse_marker.rate_hz = {pm['rate_hz']} Hz gives a {gap}-sample IPI, "
                f"which is not longer than one EOD ({eod_len} samples) — marker pulses would overlap"
            )

    # (4) The marker must stay clear of the volley rate range (volleys peak at 300-400 Hz),
    #     or it stops being distinguishable from the stimulus it introduces.
    if pm["rate_hz"] > 100.0:
        raise ValueError(
            f"sd_path.pulse_marker.rate_hz = {pm['rate_hz']} Hz is inside the volley rate range; "
            f"keep the marker well below it"
        )

    # (5) Levels are fractions of full scale.
    for name, v in sd["levels"].items():
        if not 0.0 <= v <= 1.0:
            raise ValueError(f"sd_path.levels.{name} = {v} is outside 0..1 (fraction of full scale)")

    # (6) Localization is derived as volley / ratio, so the ratio must not be zero.
    if c["rc_path"]["amp"]["volley_amp_ratio"] <= 0.0:
        raise ValueError("rc_path.amp.volley_amp_ratio must be > 0 (localization = volley / ratio)")

    # (7) The blinded draw picks one of THREE arms, so the weights are a partition, not a
    #     probability. Integer per-mille summing to exactly 1000: the C draws random(1000) and
    #     walks two cutoffs, so weights that sum to anything else silently bias the last arm
    #     (short) or make it unreachable (long) without any runtime complaint.
    trial = c["rc_path"]["trial"]
    if "p_volley" in trial:
        raise ValueError(
            "rc_path.trial.p_volley is from the two-arm (volley/sham) design and is refused "
            "by name. The trial is now three-armed — volley / baseline / silence — and needs "
            "rc_path.trial.weights. Reinstating a two-arm draw is a protocol decision, not a "
            "config edit: the baseline arm is what separates 'a discharge happened' from "
            "'a fish is present at all'."
        )
    weights = trial["weights"]
    missing = {"volley", "baseline", "silence"} - set(weights)
    if missing:
        raise ValueError(f"rc_path.trial.weights is missing {sorted(missing)}")
    if extra := set(weights) - {"volley", "baseline", "silence"}:
        raise ValueError(f"rc_path.trial.weights has unknown arms {sorted(extra)}")
    for name, w in weights.items():
        if not isinstance(w, int) or isinstance(w, bool) or w < 0:
            raise ValueError(
                f"rc_path.trial.weights.{name} = {w!r} must be a non-negative integer per-mille"
            )
    total = sum(weights.values())
    if total != 1000:
        raise ValueError(
            f"rc_path.trial.weights sum to {total}, not 1000 — the C draws random(1000) and "
            f"walks two cutoffs, so any other total silently biases or strands an arm"
        )

    # (7b) The baseline arm's own rhythm knobs. It runs its OWN LocRhythm precisely so it works
    #      with live localization off, so these cannot fall back to the CH3/CH5 controls.
    if trial["baseline_tick_hz"] <= 0.0:
        raise ValueError(
            f"rc_path.trial.baseline_tick_hz = {trial['baseline_tick_hz']} must be > 0 — it is "
            f"a tick tempo in Hz, and the rhythm divides by it"
        )
    if not 0.0 <= trial["baseline_randomness"] <= 1.0:
        raise ValueError(
            f"rc_path.trial.baseline_randomness = {trial['baseline_randomness']} is outside "
            f"0..1 (0 = metronome, 1 = the measured eel)"
        )
    # The arm's burn-in. A value at or below the ambient train's LOC_BURN_IN (40) is the
    # 2026-08-24 regression coming back by another route: the arm would start from a cold,
    # systematically SLOW state on every presentation. Measured, burn 40 draws a median first
    # interval 14 % above the model's own.
    burn = trial["baseline_burn_in"]
    if not isinstance(burn, int) or isinstance(burn, bool) or burn < 100:
        raise ValueError(
            f"rc_path.trial.baseline_burn_in = {burn!r} must be an integer >= 100. The arm "
            f"anchors a pulse and then lives under a second, so it pays the cold-start "
            f"transient in full on every presentation rather than outgrowing it."
        )

    # (8a) The CH3 rate ladder is GEOMETRIC (rc_rate_to_hz raises max/min to a fraction),
    #      so a zero or negative floor is not merely odd, it is undefined. A ladder that does
    #      not increase is equally broken.
    loc = c["rc_path"]["loc_rate"]
    if loc["min_hz"] <= 0.0:
        raise ValueError(
            f"rc_path.loc_rate.min_hz = {loc['min_hz']} — the CH3 ladder is logarithmic, so "
            f"the floor must be strictly positive"
        )
    if loc["max_hz"] <= loc["min_hz"]:
        raise ValueError("rc_path.loc_rate.max_hz must exceed min_hz")

    # (8) The RC device has no marker any more, so nothing to check here. Guard against it
    # coming back by accident rather than by decision: re-adding the block without re-adding
    # its emitter would leave a JSON key that silently generates nothing.
    if "pulse_marker" in c["rc_path"]:
        raise ValueError(
            "rc_path.pulse_marker is back in the JSON but nothing emits it. The RC marker was "
            "removed on 2026-08-22 because a sham — the no-stimulus control — was emitting four "
            "pulses before going quiet. Re-adding it is a protocol decision, not a config edit."
        )


def _f(x: float) -> str:
    """Render a float as a C float literal, stably (``0.9`` -> ``0.90f``)."""
    return f"{x!r}f" if "." in repr(x) else f"{float(x)!r}f"


def render_header(c: dict) -> str:
    """Render ``firmware/eel_core/stim_levels.h``."""
    sd, rc = c["sd_path"], c["rc_path"]
    lvl, ses = sd["levels"], sd["session"]
    sdm, cal = sd["pulse_marker"], sd["calibration"]
    amp, loc, trial = rc["amp"], rc["loc_rate"], rc["trial"]

    L = []
    a = L.append
    a(f"// {_BANNER}")
    a("//")
    a("// Playback / session constants shared by the fakefish surfaces. Edit")
    a("// shared/stim_constants.json and re-run `uv run fakefish-gen-constants`.")
    a("//")
    a("// The SAMPLE RATE is not defined here — it comes from eel_stimuli.h")
    a("// (STIM_SAMPLE_RATE_HZ), so it is stated exactly once in the whole repo. Every")
    a("// sample-unit figure below is derived from it by the preprocessor.")
    a("//")
    a("// ONE MARKER, AND ONLY THE SD DEVICE HAS IT:")
    a("//   SD_MARKER_*    6 pulses at a fixed 10 Hz with ALTERNATING polarity, baked into")
    a("//                  the WAV card by build_sd_card.py. Identifies a playback. It is that")
    a("//                  device's ONLY record — it writes no pulse log.")
    a("//   The RC device had a count-coded 100 Hz burst until 2026-08-22. Removed: its log is")
    a("//   a precondition for output, and a SHAM was emitting four pulses before going quiet.")
    a("#pragma once")
    a('#include <stdint.h>')
    a('#include "eel_stimuli.h"   // STIM_SAMPLE_RATE_HZ — the one place the rate is defined')
    a("")
    a("// ===== SD path — levels baked into the WAV card ============================")
    a("// Absolute output levels as a fraction of full scale (NOT peak-normalised): the")
    a("// loc/volley/marker ratios are the experiment, so they must survive rendering.")
    a(f"#define SD_LEVEL_VOLLEY       {_f(lvl['volley'])}")
    a(f"#define SD_LEVEL_LOC          {_f(lvl['loc'])}")
    a(f"#define SD_LEVEL_CALIBRATION  {_f(lvl['calibration'])}")
    a(f"#define SD_LEVEL_MARKER       {_f(lvl['pulse_marker'])}")
    a("")
    a("// ===== SD path — the alternating-polarity pulse marker =====================")
    a("// The lead-in that identifies a playback: SD_MARKER_N_PULSES EOD pulses at a fixed")
    a("// IPI, with the polarity ALTERNATING pulse to pulse. Alternation is the discriminator")
    a("// (no eel alternates; a localization train is single-polarity) and it survives the")
    a("// firmware's per-press random polarity flip, which negates the whole WAV. The pulse")
    a("// count is EVEN so the burst carries no net charge.")
    a(f"#define SD_MARKER_N_PULSES    {sdm['n_pulses']}")
    a(f"#define SD_MARKER_RATE_HZ     {_f(sdm['rate_hz'])}")
    a(f"#define SD_MARKER_IPI_SAMP    {ipi_samples(sdm['rate_hz'], RATE_HZ)}u   // {1000.0 / sdm['rate_hz']:.0f} ms")
    a("#define SD_MARKER_SAMP        ((uint32_t)SD_MARKER_IPI_SAMP * (SD_MARKER_N_PULSES - 1) + EOD_HV_LEN)")
    a("")
    a("// ===== SD path — program A, the calibration train ==========================")
    a("// A steady SINGLE-polarity EOD train at a known rate and level: a plain reference")
    a("// signal, deliberately not a code.")
    a(f"#define SD_CAL_RATE_HZ        {_f(cal['rate_hz'])}")
    a(f"#define SD_CAL_IPI_SAMP       {ipi_samples(cal['rate_hz'], RATE_HZ)}u")
    a(f"#define SD_CAL_S              {cal['duration_s']}")
    a("#define SD_CAL_SAMP           ((uint32_t)SD_CAL_S * STIM_SAMPLE_RATE_HZ)")
    a("")
    a("// ===== SD path — session structure =========================================")
    a("// Seconds are the authored unit; sample units are derived from STIM_SAMPLE_RATE_HZ.")
    a(f"#define SD_SESSION_LOC_S         {ses['loc_s']}   // localization window (program B)")
    a(f"#define SD_SESSION_D_LOC_S       {ses['d_loc_s']}    // localization lead (program D)")
    a(f"#define SD_SESSION_D_GAP_MS      {ses['d_gap_ms']}  // loc -> volley gap (program D)")
    a("#define SD_SESSION_LOC_SAMP      ((uint32_t)SD_SESSION_LOC_S    * STIM_SAMPLE_RATE_HZ)")
    a("#define SD_SESSION_D_LOC_SAMP    ((uint32_t)SD_SESSION_D_LOC_S  * STIM_SAMPLE_RATE_HZ)")
    a("#define SD_SESSION_D_GAP_SAMP    ((uint32_t)SD_SESSION_D_GAP_MS * STIM_SAMPLE_RATE_HZ / 1000u)")
    a("")
    a("// Nominal open-circuit pulse peak at full scale. NOT a calibrated field strength —")
    a("// in water the source impedance divides against the load. Operator-set nominal only.")
    a(f"#define SD_FULLSCALE_PULSE_PEAK_MV {_f(sd['fullscale_pulse_peak_mv'])}")
    a("")
    a("// ===== RC path — NO MARKER ================================================")
    a("// The RC device emitted a count-coded EOD burst before every trial (2 pulses volley,")
    a("// 4 sham, 100 Hz) until 2026-08-22. PULSE_MARKER_* is gone: the per-pulse SD log is a")
    a("// precondition for output, so the trial was already recorded — and for a SHAM the burst")
    a("// was not redundant at all, it was a stimulus in the no-stimulus control.")
    a("// The SD device keeps SD_MARKER_* above; it has no log, so its lead-in is the only")
    a("// record a playback happened.")
    a("")
    w = trial["weights"]
    a("// ===== RC path — blinded THREE-ARM trial draw ==============================")
    a("// The trigger fires in ONE direction and does not say WHICH arm to run; the firmware")
    a("// draws at playback time, so the operator cannot choose and their timing cannot")
    a("// correlate with the arm. The draw happens in the sample-clock ISR, never in loop(),")
    a("// because random() must stay single-caller.")
    a("//")
    a("//   VOLLEY   — a library discharge (the treatment)")
    a("//   BASELINE — resting-rhythm pulses at localization amplitude: a fish is present and")
    a("//              NOT hunting. This is the arm that separates 'a discharge happened' from")
    a("//              'a fish is there at all', which a volley-vs-nothing design confounds.")
    a("//   SILENCE  — nothing at all (what the two-arm design called a SHAM).")
    a("//")
    a("// All three last the SAME length: every trial draws a volley item and the two silent")
    a("// arms hold for exactly its duration, so the arms match in duration BY CONSTRUCTION.")
    a("// Weights are per-mille and sum to 1000 (gen_constants.validate enforces it); the C")
    a("// draws random(TRIAL_DRAW_RANGE) once and walks the two cutoffs in this order.")
    a(f"#define TRIAL_W_VOLLEY_MILLI   {w['volley']}   // per-mille; the three sum to 1000")
    a(f"#define TRIAL_W_BASELINE_MILLI {w['baseline']}")
    a(f"#define TRIAL_W_SILENCE_MILLI  {w['silence']}")
    a("#define TRIAL_DRAW_RANGE       1000   // draw random(TRIAL_DRAW_RANGE)...")
    a("#define TRIAL_CUT_VOLLEY       (TRIAL_W_VOLLEY_MILLI)                          // ...< this = VOLLEY")
    a("#define TRIAL_CUT_BASELINE     (TRIAL_W_VOLLEY_MILLI + TRIAL_W_BASELINE_MILLI) // ...< this = BASELINE, else SILENCE")
    a("")
    a("// The BASELINE arm's own rhythm knobs, deliberately NOT the CH3/CH5 controls: the")
    a("// control condition is 'a resting eel', not 'a resting eel at whatever tempo the knob")
    a("// was left at' — and the arm must work with live localization switched fully off,")
    a("// which is exactly when CH3 reads REST. 3.15 Hz is the measured animal.")
    a(f"#define TRIAL_BASE_TICK_HZ     {_f(trial['baseline_tick_hz'])}")
    a(f"#define TRIAL_BASE_RANDOMNESS  {_f(trial['baseline_randomness'])}")
    a("")
    a("// Intervals to run a FRESH arm rhythm forward before the arm uses it. The arm observes")
    a("// the fish at its own PULSES while the model's stationary law is in continuous time, so")
    a("// a cold state starts slow — and an arm lives a fraction of a second, so it pays that")
    a("// transient in full every time instead of outgrowing it as the ambient train does.")
    a("// Measured on the shipped C: burn 40 -> +14.2 % on the median first interval, 320 ->")
    a("// +5.3 %, 1000 -> +3.1 %. Convergence is slow (the slowest component relaxes over 62")
    a("// minutes), so this is a compromise. NOT LOC_BURN_IN, which is generated (invariant 11).")
    a(f"#define TRIAL_BASE_BURN_IN     {trial['baseline_burn_in']}")
    a("")
    a("// ===== RC path — amplitude =================================================")
    a("// The control sets the VOLLEY (max); localization is DERIVED as volley / ratio.")
    a(f"#define VOLLEY_AMP_RATIO   {_f(amp['volley_amp_ratio'])}")
    a(f"#define MASTER_AMP_MIN     {_f(amp['master_min'])}")
    a(f"#define MASTER_AMP_MAX     {_f(amp['master_max'])}")
    a(f"#define PANEL_VOLLEY_AMP   {_f(amp['panel_volley_amp'])} // bench default (no transmitter)")
    a("")
    a("// ===== RC path — live localization train ===================================")
    a("// The RHYTHM is the fitted model (loc_model_params.h + loc_rhythm.h); these are only")
    a("// the ranges the operator's knobs span.")
    a("//")
    a("// CH3 is a TICK TEMPO — one over the median interval — not an average pulse rate. The")
    a("// measured eel ticks at LOC_NOMINAL_TICK_HZ (3.15 Hz). Under the retired lognormal a")
    a("// setting of 5 Hz meant 5 pulses/s on average; it now means the fish ticks at 5 Hz,")
    a("// which delivers about 3.3 pulses/s once the heavy tail is included.")
    a("//")
    a("// The ladder between these two is LOGARITHMIC (rc_rate_to_hz), so every rung is the same")
    a("// RATIO from its neighbours. A linear one spent ~85 % of the throttle's travel above")
    a("// anything a real eel does and pushed the slow settings into the sliver of travel just")
    a("// above the fail-safe cutoff. Geometric spacing puts the measured eel at mid-throttle")
    a(f"// (sqrt({loc['min_hz']} * {loc['max_hz']}) = "
      f"{(loc['min_hz'] * loc['max_hz']) ** 0.5:.2f} Hz) and gives ~0.1 Hz steps near 1 Hz.")
    a(f"#define LOC_RATE_MIN_HZ    {_f(loc['min_hz'])}")
    a(f"#define LOC_RATE_MAX_HZ    {_f(loc['max_hz'])}")
    a(f"#define PANEL_RATE_HZ      {_f(loc['panel_rate_hz'])}")
    a("// CH5 bench default. 1.0 IS the measured eel (0 = metronome, useful to ~1.5). This is")
    a("// NOT the retired jitter CV: it scales the state score, so it changes how MUCH the rate")
    a("// varies without touching how it varies over time.")
    a(f"#define PANEL_RANDOMNESS   {_f(loc['panel_randomness'])}")
    a("// Minimum IPI. MUST stay > EOD_HV_LEN so localization pulses can never overlap —")
    a("// that invariant is what lets locgen.h use a single-pulse scheduler.")
    a("//")
    a("// This is the RESTING/VOLLEY ANTIMODE, not an arbitrary margin. The model's interval")
    a("// table is clamped to it in SCORE space, but rate is a pure TIME dilation, so any")
    a("// tick tempo above the nominal 3.15 Hz scales that floor down with everything else")
    a("// (4.4 ms at CH3 = 20 Hz). Since the source analysis separates resting pulses from")
    a("// fast runs on exactly this antimode, an unfloored fast train would emit intervals")
    a("// that read as micro-bursts of our own making.")
    a(f"#define LOC_REFRACTORY_SAMP {loc['refractory_samp']}u  "
      f"// {1000.0 * loc['refractory_samp'] / RATE_HZ:.0f} ms @ {RATE_HZ // 1000} kHz")
    a("")
    return "\n".join(L)


def render_python(c: dict) -> str:
    """Render ``src/fakefish/_constants.py`` (the SD-path group the toolchain consumes)."""
    sd = c["sd_path"]
    lvl, ses = sd["levels"], sd["session"]
    sdm, cal = sd["pulse_marker"], sd["calibration"]

    L = []
    a = L.append
    a(f'"""{_BANNER}')
    a("")
    a("Playback/session constants for the SD-card path, generated from")
    a("``shared/stim_constants.json``. ``build_sd_card.py`` bakes these into the WAV card")
    a("and ``_gallery_marker.py`` draws the galleries at the same levels, so the figures")
    a("and the card can no longer drift apart.")
    a("")
    a("The sample rate is NOT restated here — it is imported from the export tool, which")
    a("is where it is defined once for the whole repo.")
    a('"""')
    a("")
    a("from __future__ import annotations")
    a("")
    a("from fakefish.export_teensy_stimuli import PLAYBACK_RATE_HZ as RATE_HZ")
    a("")
    a("# ===== Absolute output levels (fraction of full scale) ==============================")
    a(f"VOLLEY_AMPLITUDE = {lvl['volley']!r}")
    a(f"LOC_AMPLITUDE = {lvl['loc']!r}")
    a(f"CAL_AMPLITUDE = {lvl['calibration']!r}")
    a(f"MARKER_AMPLITUDE = {lvl['pulse_marker']!r}")
    a("")
    a("# ===== The alternating-polarity pulse marker (the lead-in) ==========================")
    a("#: EVEN by construction, so the burst is charge-balanced; alternation is what")
    a("#: identifies it, and alternation survives the firmware's per-press polarity flip.")
    a(f"MARKER_N_PULSES = {sdm['n_pulses']!r}")
    a(f"MARKER_RATE_HZ = {sdm['rate_hz']!r}")
    a(f"MARKER_IPI_SAMPLES = {ipi_samples(sdm['rate_hz'], RATE_HZ)!r}")
    a("#: First onset to last onset (the burst's span, excluding the final pulse's tail).")
    a(f"MARKER_SPAN_SAMPLES = {ipi_samples(sdm['rate_hz'], RATE_HZ) * (sdm['n_pulses'] - 1)!r}")
    a(f"MARKER_SPAN_S = {ipi_samples(sdm['rate_hz'], RATE_HZ) * (sdm['n_pulses'] - 1) / RATE_HZ!r}")
    a("")
    a("# ===== Program A: the calibration train =============================================")
    a(f"CAL_RATE_HZ = {cal['rate_hz']!r}")
    a(f"CAL_IPI_SAMPLES = {ipi_samples(cal['rate_hz'], RATE_HZ)!r}")
    a(f"CAL_S = {float(cal['duration_s'])!r}")
    a(f"CAL_SAMPLES = {cal['duration_s']} * RATE_HZ")
    a("")
    a("# ===== Session structure ============================================================")
    a(f"LOC_PLAYBACK_S = {float(ses['loc_s'])!r}")
    a(f"D_LOC_PLAYBACK_S = {float(ses['d_loc_s'])!r}")
    a(f"D_INTERPHASE_GAP_S = {ses['d_gap_ms'] / 1000.0!r}")
    a("")
    a(f"LOC_PLAYBACK_SAMPLES = {ses['loc_s']} * RATE_HZ")
    a(f"D_LOC_PLAYBACK_SAMPLES = {ses['d_loc_s']} * RATE_HZ")
    a(f"D_INTERPHASE_GAP_SAMPLES = {ses['d_gap_ms']} * RATE_HZ // 1000")
    a("")
    a("# ===== Nominal mV map ===============================================================")
    a("#: Nominal OPEN-CIRCUIT pulse peak at full scale, not a calibrated field strength.")
    a(f"FULLSCALE_PULSE_PEAK_MV = {sd['fullscale_pulse_peak_mv']!r}")
    a("")
    return "\n".join(L)


# ===== the vendored resting-rhythm model -> C ==========================================
#
# WHY THIS IS GENERATED AND NOT TYPED OUT. ``LOCALIZATION_GENERATIVE_SPEC.md`` §7 ships a
# ready-to-paste C listing, and pasting it would be wrong: as dropped on 2026-08-21 that
# listing disagrees with the fitted parameters it claims to implement — ``TAU[0]`` 3.200
# against a shipped ``tau_fast_s`` of 2.5, ``HAZ_B0`` −4.872 against −4.8118, and both
# mixture widths off in the third decimal. The JSON is the self-consistent one (its
# interval table was calibrated AT tau 2.5, and running the reference sampler with it
# reproduces the spec's own §6 validation column, while substituting 3.2 moves the median
# interval off the measured 317 ms). Deriving the header from the JSON makes that whole
# class of transcription error impossible instead of merely discouraged.

#: Burn-in intervals discarded at power-on. The components' stationary distribution is
#: defined in continuous time while the model is observed at its own pulse times, so a
#: cold state starts noticeably slow; the reference implementation's ``new_state`` default.
LOC_BURN_IN = 40


def load_loc_model(path: Path = LOC_MODEL_JSON) -> dict:
    """Read the vendored fitted parameters (no ``_comment`` convention here)."""
    return json.loads(path.read_text())


def _uniform_step(values: list[float], label: str) -> float:
    """Assert a grid is evenly spaced and return its step.

    Load-bearing: the C looks both tables up with O(1) index arithmetic
    (``i = (x - lo) / step``) rather than a search, which is only equivalent to the
    reference's ``np.interp`` while the grid is uniform. A re-drop that re-spaced either
    grid would otherwise index silently wrong — the model would still run, and every
    interval it produced would come from the wrong knot.
    """
    if len(values) < 2:
        raise ValueError(f"{label}: need at least two knots, got {len(values)}")
    step = (values[-1] - values[0]) / (len(values) - 1)
    for i, v in enumerate(values):
        if abs(v - (values[0] + i * step)) > 1e-9:
            raise ValueError(
                f"{label} is not evenly spaced at index {i} ({v} vs "
                f"{values[0] + i * step}) — loc_rhythm.h indexes it by arithmetic, so a "
                f"non-uniform grid must be looked up by search instead"
            )
    return step


def validate_loc_model(p: dict) -> None:
    """Fail loudly on a re-drop that breaks what the C port assumes."""
    st, mg, kn, nz = p["state"], p["marginal"], p["knobs"], p["noise"]

    # (1) The variances sum to 1 BY CONSTRUCTION — that is what makes the score standard
    #     normal and therefore makes the quantile table *be* the interval distribution.
    total = sum(st[k] for k in ("var_fast", "var_medium", "var_slow", "var_offset", "var_white"))
    if abs(total - 1.0) > 1e-6:
        raise ValueError(f"state variances sum to {total}, not 1 — the score is not standard normal")

    # (2) Both grids must be uniform (see _uniform_step) ...
    _uniform_step(mg["z_knots"], "marginal.z_knots")
    _uniform_step(kn["randomness"], "knobs.randomness")
    if kn["randomness"][0] != 0.0:
        raise ValueError("knobs.randomness must start at 0 (the metronome end of the knob)")

    # (3) ... and the interval table must be a quantile function, i.e. monotone. A
    #     non-monotone table would map a faster state to a longer interval.
    knots = mg["log_ipi_knots"]
    if any(b <= a for a, b in zip(knots[:-1], knots[1:], strict=True)):
        raise ValueError("marginal.log_ipi_knots is not strictly increasing")
    if len(knots) != len(mg["z_knots"]):
        raise ValueError("marginal.log_ipi_knots and z_knots differ in length")

    # (4) The gain table is what holds the tick tempo where the rate knob says it is, so at
    #     randomness 1.0 — the measured eel, the knob's definition point — it must be 1.
    i_one = kn["randomness"].index(1.0)
    if abs(kn["gain_median_anchor"][i_one] - 1.0) > 1e-6:
        raise ValueError(
            f"knobs.gain_median_anchor at randomness 1.0 is "
            f"{kn['gain_median_anchor'][i_one]}, not 1.0 — the rate knob would be "
            f"mis-scaled at its own reference point"
        )
    if len(kn["gain_median_anchor"]) != len(kn["randomness"]):
        raise ValueError("knobs.gain_median_anchor and knobs.randomness differ in length")

    # (5) The noise mixture is unit-variance by construction (mix_p*lo^2 + (1-p)*hi^2 == 1);
    #     if it is not, every variance in the state table is silently rescaled.
    var = nz["mix_p"] * nz["mix_sd_lo"] ** 2 + (1.0 - nz["mix_p"]) * nz["mix_sd_hi"] ** 2
    if abs(var - 1.0) > 1e-3:
        raise ValueError(f"noise mixture variance is {var}, not 1")


def render_loc_header(p: dict, rate_hz: int, eod_len: int | None = None) -> str:
    """Render ``firmware/eel_core/loc_model_params.h`` from the vendored parameters."""
    st, mg, kn, nz = p["state"], p["marginal"], p["knobs"], p["noise"]
    ref, prov = p["reference_statistics"], p["provenance"]

    z = mg["z_knots"]
    z_step = _uniform_step(z, "marginal.z_knots")
    s_step = _uniform_step(kn["randomness"], "knobs.randomness")
    taus = [st["tau_fast_s"], st["tau_medium_s"], st["tau_slow_s"]]
    sds = [st["var_fast"] ** 0.5, st["var_medium"] ** 0.5, st["var_slow"] ** 0.5]
    ipi_lo = 2.718281828459045 ** mg["log_ipi_knots"][0]
    ipi_hi = 2.718281828459045 ** mg["log_ipi_knots"][-1]

    def table(name: str, values: list[float], dim: str, per_line: int = 4) -> list[str]:
        # Sized by the count macro on purpose: the C indexes these by arithmetic derived
        # from the same macro, so a table and its count going out of step must be a
        # compile error rather than a read past the end.
        out = [f"static const float {name}[{dim}] = {{"]
        for i in range(0, len(values), per_line):
            out.append("  " + " ".join(_f(v) + "," for v in values[i:i + per_line]))
        out.append("};")
        return out

    L: list[str] = []
    a = L.append
    a(f"// {_LOC_BANNER}")
    a("//")
    a("// The FITTED resting localization rhythm of Electrophorus — the tables consumed by")
    a("// loc_rhythm.h. Fitted in eeltracker (analyses/localization_rhythm) to 29 h of")
    a(f"// single-eel stretches: {prov['n_resting_intervals']} resting intervals over "
      f"{prov['n_slices']} slices,")
    a(f"// {prov['n_recordings_used']} recordings, {prov['n_sites']} sites of {prov['dataset']}.")
    a("// Provenance and every caveat: docs/LOCALIZATION_GENERATIVE_SPEC.md.")
    a("//")
    a("// DO NOT hand-type these from the spec's §7 listing — it disagrees with the fitted")
    a("// parameters (tau_fast, the hazard intercept and both mixture widths). Edit nothing")
    a("// here: re-drop data/loc_model_params.json from eeltracker and re-run the codegen.")
    a("//")
    a("// The BURST HAZARD is deliberately absent. The model's interrupt() — the fish's own")
    a("// decision to fire a fast run — is not ported: this device only ever emits an")
    a("// operator-requested volley, so that every volley in the water carries a marker and a")
    a("// sham is true silence. See loc_rhythm.h and CLAUDE.md.")
    a("#pragma once")
    a("")
    a("// ===== state: Ornstein-Uhlenbeck components relaxing in WALL-CLOCK time ====")
    a("// Not in pulse count. After a 3 s silence the fish has forgotten more than after")
    a("// three 100 ms intervals, and refitting per-pulse costs 699 nats (spec §2.2).")
    a(f"#define LOC_N_COMPONENTS {len(taus)}")
    a("")
    a("// Time constants (s): fast, medium, slow.")
    L.extend(table("LOC_TAU_S", taus, "LOC_N_COMPONENTS", 3))
    a("// Component sds in score units (sqrt of each variance; they sum to 1 with the white")
    a("// and offset terms, which is what makes the score standard normal).")
    L.extend(table("LOC_SD", sds, "LOC_N_COMPONENTS", 3))
    a(f"#define LOC_SD_WHITE  {_f(st['var_white'] ** 0.5)}  // fresh jitter, per pulse")
    a(f"#define LOC_SD_OFFSET {_f(st['var_offset'] ** 0.5)}  // per-power-on tempo offset")
    a("")
    a("// ===== noise: PEAKED, not Gaussian =========================================")
    a("// A unit-variance two-scale Gaussian mixture. The fish holds its rate almost exactly")
    a("// and then jumps (measured excess kurtosis +1.5); Gaussian noise of the same variance")
    a("// gets the interval distribution right and still sounds wrong — median CV2 0.60")
    a(f"// against a measured {nz['measured_cv2_pooled']:.3f}. One extra uniform and a branch.")
    a(f"#define LOC_MIX_P     {_f(nz['mix_p'])}")
    a(f"#define LOC_MIX_SD_LO {_f(nz['mix_sd_lo'])}")
    a(f"#define LOC_MIX_SD_HI {_f(nz['mix_sd_hi'])}")
    a("")
    a("// ===== the interval quantile table =========================================")
    a("// score -> log(interval in seconds), linearly interpolated, CLAMPED at both ends.")
    a("// The clamp is deliberate: the bottom is the 25 ms resting/volley antimode, so the")
    a("// resting rhythm can never intrude into volley territory, and the top is the 99.98th")
    a("// percentile of the measured intervals, beyond which there is nothing to extrapolate.")
    a("//")
    a("// CALIBRATED, and the calibration is load-bearing: the model is observed at its own")
    a("// pulse times, which over-visits the fast side, so feeding the raw measured quantiles")
    a("// in would run the device 43 % fast. marginal.uncalibrated_ipi_ms_knots in the JSON is")
    a("// the raw distribution — for comparison, never as the table.")
    a(f"#define LOC_N_KNOTS   {len(z)}")
    a(f"#define LOC_Z_LO      {_f(z[0])}")
    a(f"#define LOC_Z_HI      {_f(z[-1])}")
    a(f"#define LOC_Z_STEP    {_f(z_step)}")
    a(f"#define LOC_Z_SCALE   {_f(1.0 / z_step)}  // (z - LOC_Z_LO) * this == knot index")
    L.extend(table("LOC_LOG_IPI_KNOTS", mg["log_ipi_knots"], "LOC_N_KNOTS"))
    a(f"// Table range: {1e3 * ipi_lo:.1f} ms .. {ipi_hi:.1f} s at tempo 1.")
    a(f"#define LOC_IPI_MIN_S {_f(ipi_lo)}")
    a(f"#define LOC_IPI_MAX_S {_f(ipi_hi)}")
    if eod_len is not None:
        a(f"// The fastest interval the table can produce is {1e3 * ipi_lo:.1f} ms == "
          f"{round(ipi_lo * rate_hz)} samples")
        a(f"// at tempo 1, against a {eod_len}-sample EOD, so locgen's no-overlap invariant")
        a("// holds with a wide margin until the rate knob is turned well past a real eel.")
    a("")
    a("// ===== the randomness knob's gain table ====================================")
    a("// 0 = a metronome at exactly the nominal tempo, 1 = the measured eel, useful to ~1.5.")
    a("// The knob scales the state score; this table then holds the TICK TEMPO (1 / median")
    a("// interval) where the rate knob says it is as the score's spread changes. Without it,")
    a("// randomness 0 would emit the calibrated table's own score-zero knot instead of the")
    a("// fish's median.")
    a("//")
    a("// MEDIAN ANCHOR. A heavy-tailed interval distribution cannot hold its median and its")
    a("// mean at once. This device holds the median — the tick tempo, the number quoted as an")
    a("// eel's discharge rate — so the CH3 throttle's Hz scale keeps meaning 'the fish ticks")
    a("// at this rate'. The cost is that sweeping randomness moves the dose (3.9 -> 1.1")
    a("// pulses/s across the knob). knobs.gain_mean_anchor in the JSON is the other table,")
    a("// which holds the dose instead — what the retired lognormal knob meant. Switching")
    a("// anchors means rendering that table here and re-reading spec §5.3.")
    a(f"#define LOC_KNOB_N     {len(kn['randomness'])}")
    a(f"#define LOC_KNOB_STEP  {_f(s_step)}")
    a(f"#define LOC_KNOB_SCALE {_f(1.0 / s_step)}  // randomness * this == knob index")
    a(f"#define LOC_KNOB_MAX   {_f(kn['randomness'][-1])}")
    L.extend(table("LOC_KNOB_GAIN", kn["gain_median_anchor"], "LOC_KNOB_N"))
    a("")
    a("// ===== reference points ====================================================")
    a("// The measured tick tempo: 1 / the median resting interval. This is what rate == 1")
    a("// means, and it is what converts the CH3 throttle's Hz setting into a tempo multiplier.")
    a("// NOTE the other rate number, deliberately not used here: a single eel emits about")
    a("// 1.1 pulses/s averaged over a slice. Both are right — the distribution is")
    a("// heavy-tailed. Quote this one for 'how fast does it tick'.")
    a(f"#define LOC_NOMINAL_TICK_HZ {_f(ref['resting_ipi_median_hz'])}")
    a(f"#define LOC_MEDIAN_IPI_MS   {_f(ref['resting_ipi_ms']['50'])}")
    a("// Intervals discarded at power-on to clear the cold-start transient (spec §7).")
    a(f"#define LOC_BURN_IN         {LOC_BURN_IN}")
    a("")
    return "\n".join(L)


def generate(source: Path = SOURCE_JSON) -> dict[Path, str]:
    """Render every output. Returns ``{path: content}`` without writing anything."""
    c = load_constants(source)
    eod_len = _eod_hv_len()
    validate(c, RATE_HZ, eod_len=eod_len)
    loc = load_loc_model()
    validate_loc_model(loc)
    return {
        OUT_HEADER: render_header(c),
        OUT_PYTHON: render_python(c),
        OUT_LOC_HEADER: render_loc_header(loc, RATE_HZ, eod_len=eod_len),
    }


@app.command()
def main(
    check: bool = typer.Option(
        False, "--check", help="Do not write; exit non-zero if a generated file is stale."
    ),
    verbose: int = typer.Option(0, "--verbose", "-v", count=True, help="-v INFO, -vv DEBUG."),
) -> None:
    """Regenerate ``stim_levels.h`` + ``_constants.py`` from ``shared/stim_constants.json``."""
    configure_logging(verbose)
    rendered = generate()

    stale = []
    for path, content in rendered.items():
        current = path.read_text() if path.exists() else None
        if current == content:
            log.info("up to date: %s", path)
            continue
        stale.append(path)
        if check:
            log.error("STALE: %s", path)
        else:
            path.write_text(content)
            log.info("wrote %s", path)

    if check:
        if stale:
            names = ", ".join(str(p) for p in stale)
            typer.echo(
                f"STALE (re-run fakefish-gen-constants and commit): {names}", err=True
            )
            raise typer.Exit(code=1)
        typer.echo(f"up to date: {len(rendered)} generated file(s)")
        return
    typer.echo(f"generated {len(rendered)} file(s) from {SOURCE_JSON.name}")


if __name__ == "__main__":
    app()
