// GENERATED by fakefish-gen-constants from data/loc_model_params.json — DO NOT EDIT.
//
// The FITTED resting localization rhythm of Electrophorus — the tables consumed by
// loc_rhythm.h. Fitted in eeltracker (analyses/localization_rhythm) to 29 h of
// single-eel stretches: 99010 resting intervals over 1761 slices,
// 42 recordings, 15 sites of FLONA 2025.
// Provenance and every caveat: docs/LOCALIZATION_GENERATIVE_SPEC.md.
//
// DO NOT hand-type these from the spec's §7 listing — it disagrees with the fitted
// parameters (tau_fast, the hazard intercept and both mixture widths). Edit nothing
// here: re-drop data/loc_model_params.json from eeltracker and re-run the codegen.
//
// The BURST HAZARD is deliberately absent. The model's interrupt() — the fish's own
// decision to fire a fast run — is not ported: this device only ever emits an
// operator-requested volley, so that every volley in the water carries a marker and a
// sham is true silence. See loc_rhythm.h and CLAUDE.md.
#pragma once

// ===== state: Ornstein-Uhlenbeck components relaxing in WALL-CLOCK time ====
// Not in pulse count. After a 3 s silence the fish has forgotten more than after
// three 100 ms intervals, and refitting per-pulse costs 699 nats (spec §2.2).
#define LOC_N_COMPONENTS 3

// Time constants (s): fast, medium, slow.
static const float LOC_TAU_S[LOC_N_COMPONENTS] = {
  2.5f, 95.75374303072176f, 3726.0673712325997f,
};
// Component sds in score units (sqrt of each variance; they sum to 1 with the white
// and offset terms, which is what makes the score standard normal).
static const float LOC_SD[LOC_N_COMPONENTS] = {
  0.6603548261510097f, 0.33141171911122286f, 0.24629752382756123f,
};
#define LOC_SD_WHITE  0.615753358676818f  // fresh jitter, per pulse
#define LOC_SD_OFFSET 0.11951195358391332f  // per-power-on tempo offset

// ===== noise: PEAKED, not Gaussian =========================================
// A unit-variance two-scale Gaussian mixture. The fish holds its rate almost exactly
// and then jumps (measured excess kurtosis +1.5); Gaussian noise of the same variance
// gets the interval distribution right and still sounds wrong — median CV2 0.60
// against a measured 0.382. One extra uniform and a branch.
#define LOC_MIX_P     0.7f
#define LOC_MIX_SD_LO 0.3461268178481371f
#define LOC_MIX_SD_HI 1.7475099982321758f

// ===== the interval quantile table =========================================
// score -> log(interval in seconds), linearly interpolated, CLAMPED at both ends.
// The clamp is deliberate: the bottom is the 25 ms resting/volley antimode, so the
// resting rhythm can never intrude into volley territory, and the top is the 99.98th
// percentile of the measured intervals, beyond which there is nothing to extrapolate.
//
// CALIBRATED, and the calibration is load-bearing: the model is observed at its own
// pulse times, which over-visits the fast side, so feeding the raw measured quantiles
// in would run the device 43 % fast. marginal.uncalibrated_ipi_ms_knots in the JSON is
// the raw distribution — for comparison, never as the table.
#define LOC_N_KNOTS   41
#define LOC_Z_LO      -3.5f
#define LOC_Z_HI      3.5f
#define LOC_Z_STEP    0.175f
#define LOC_Z_SCALE   5.714285714285714f  // (z - LOC_Z_LO) * this == knot index
static const float LOC_LOG_IPI_KNOTS[LOC_N_KNOTS] = {
  -3.5796351106518305f, -3.397405552514056f, -3.327131536907242f, -3.2429466776699822f,
  -3.1522875371488537f, -3.0640750427813694f, -2.9754219640834716f, -2.8699502945932527f,
  -2.7548558983239504f, -2.6313082668769785f, -2.4964641436347215f, -2.34187966567097f,
  -2.1646305144826f, -1.9584628369496937f, -1.7218605924879582f, -1.4888002206328528f,
  -1.2910201725291301f, -1.121181590271982f, -0.9775922815236102f, -0.8383340335633858f,
  -0.6727549188285401f, -0.4633617217648837f, -0.23178219646233347f, 0.010824768077025697f,
  0.2500056767547405f, 0.49071414467367647f, 0.7285823548029025f, 0.9586032786639135f,
  1.187700918507643f, 1.4133441626470375f, 1.6800174175307876f, 1.925615417735194f,
  2.1678924908245905f, 2.405060102294426f, 2.636773962250257f, 2.8460809732162176f,
  3.022089192165991f, 3.161576981309766f, 3.260488724148108f, 3.3920621232894805f,
  3.469166862097487f,
};
// Table range: 27.9 ms .. 32.1 s at tempo 1.
#define LOC_IPI_MIN_S 0.027885871656583166f
#define LOC_IPI_MAX_S 32.10997925682033f
// The fastest interval the table can produce is 27.9 ms == 1394 samples
// at tempo 1, against a 131-sample EOD, so locgen's no-overlap invariant
// holds with a wide margin until the rate knob is turned well past a real eel.

// ===== the randomness knob's gain table ====================================
// 0 = a metronome at exactly the nominal tempo, 1 = the measured eel, useful to ~1.5.
// The knob scales the state score; this table then holds the TICK TEMPO (1 / median
// interval) where the rate knob says it is as the score's spread changes. Without it,
// randomness 0 would emit the calibrated table's own score-zero knot instead of the
// fish's median.
//
// MEDIAN ANCHOR. A heavy-tailed interval distribution cannot hold its median and its
// mean at once. This device holds the median — the tick tempo, the number quoted as an
// eel's discharge rate — so the CH3 throttle's Hz scale keeps meaning 'the fish ticks
// at this rate'. The cost is that sweeping randomness moves the dose (3.9 -> 1.1
// pulses/s across the knob). knobs.gain_mean_anchor in the JSON is the other table,
// which holds the dose instead — what the retired lognormal knob meant. Switching
// anchors means rendering that table here and re-reading spec §5.3.
#define LOC_KNOB_N     21
#define LOC_KNOB_STEP  0.1f
#define LOC_KNOB_SCALE 10.0f  // randomness * this == knob index
#define LOC_KNOB_MAX   2.0f
static const float LOC_KNOB_GAIN[LOC_KNOB_N] = {
  0.6691695431479716f, 0.6725020781939992f, 0.6788896144989138f, 0.6949693977756146f,
  0.7144657467433678f, 0.7392171779309746f, 0.7765118721335951f, 0.8220712300831271f,
  0.8737713706264021f, 0.9296685749614925f, 1.0f, 1.0884853477025338f,
  1.194754581831806f, 1.3265745104857247f, 1.4794087409441528f, 1.7361253966564958f,
  1.9674071989864523f, 2.3642621501068297f, 2.653272501515727f, 3.0294357717779063f,
  3.32119609316587f,
};

// ===== reference points ====================================================
// The measured tick tempo: 1 / the median resting interval. This is what rate == 1
// means, and it is what converts the CH3 throttle's Hz setting into a tempo multiplier.
// NOTE the other rate number, deliberately not used here: a single eel emits about
// 1.1 pulses/s averaged over a slice. Both are right — the distribution is
// heavy-tailed. Quote this one for 'how fast does it tick'.
#define LOC_NOMINAL_TICK_HZ 3.1531235629817855f
#define LOC_MEDIAN_IPI_MS   317.1458333381452f
// Intervals discarded at power-on to clear the cold-start transient (spec §7).
#define LOC_BURN_IN         40
